// @ts-nocheck
import { ExecArgs } from "@medusajs/framework/types"
import {
  ContainerRegistrationKeys,
  Modules,
} from "@medusajs/framework/utils"
import {
  createProductsWorkflow,
  createProductCategoriesWorkflow,
} from "@medusajs/medusa/core-flows"

export default async function seedProductsRich({ container }: ExecArgs) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const query = container.resolve(ContainerRegistrationKeys.QUERY)
  const salesChannelService = container.resolve(Modules.SALES_CHANNEL)

  logger.info("========================================")
  logger.info("Starting Rich Product Seed (40+ products)")
  logger.info("========================================")

  const channels = await salesChannelService.listSalesChannels({})
  const channelIds = channels.map((c) => ({ id: c.id }))
  logger.info(`  Found ${channels.length} sales channels`)

  const { data: existingCategories } = await query.graph({
    entity: "product_category",
    fields: ["id", "handle"],
  })
  const existingHandles = new Set((existingCategories || []).map((c: any) => c.handle))

  const categoryDefs = [
    { name: "Fashion & Apparel", handle: "fashion-apparel", is_active: true, is_internal: false },
    { name: "Electronics & Gadgets", handle: "electronics-gadgets", is_active: true, is_internal: false },
    { name: "Home & Living", handle: "home-living", is_active: true, is_internal: false },
    { name: "Food & Beverages", handle: "food-beverages-rich", is_active: true, is_internal: false },
    { name: "Health & Beauty", handle: "health-beauty", is_active: true, is_internal: false },
    { name: "Automotive & Parts", handle: "automotive-parts", is_active: true, is_internal: false },
    { name: "Real Estate & Property", handle: "real-estate-property", is_active: true, is_internal: false },
    { name: "Travel & Tourism", handle: "travel-tourism", is_active: true, is_internal: false },
    { name: "Education & Training", handle: "education-training", is_active: true, is_internal: false },
    { name: "Healthcare & Medical", handle: "healthcare-medical", is_active: true, is_internal: false },
    { name: "Sports & Fitness", handle: "sports-fitness", is_active: true, is_internal: false },
    { name: "Pets & Animals", handle: "pets-animals", is_active: true, is_internal: false },
    { name: "Legal Services", handle: "legal-services", is_active: true, is_internal: false },
    { name: "Financial Services", handle: "financial-services", is_active: true, is_internal: false },
    { name: "Government Services", handle: "government-services", is_active: true, is_internal: false },
    { name: "Restaurant & Dining", handle: "restaurant-dining", is_active: true, is_internal: false },
    { name: "Grocery & Fresh", handle: "grocery-fresh", is_active: true, is_internal: false },
    { name: "Digital Products", handle: "digital-products", is_active: true, is_internal: false },
    { name: "Arts & Crafts", handle: "arts-crafts", is_active: true, is_internal: false },
    { name: "Books & Media", handle: "books-media", is_active: true, is_internal: false },
    { name: "Jewelry & Watches", handle: "jewelry-watches", is_active: true, is_internal: false },
    { name: "Children & Baby", handle: "children-baby", is_active: true, is_internal: false },
    { name: "Garden & Outdoor", handle: "garden-outdoor", is_active: true, is_internal: false },
    { name: "Office & Business", handle: "office-business", is_active: true, is_internal: false },
    { name: "Oud & Perfumes", handle: "oud-perfumes", is_active: true, is_internal: false },
    { name: "Traditional Clothing", handle: "traditional-clothing", is_active: true, is_internal: false },
    { name: "Saudi Specialties", handle: "saudi-specialties", is_active: true, is_internal: false },
  ]

  const categoriesToCreate = categoryDefs.filter((c) => !existingHandles.has(c.handle))

  if (categoriesToCreate.length > 0) {
    try {
      const { result: catResult } = await createProductCategoriesWorkflow(container).run({
        input: { product_categories: categoriesToCreate },
      })
      logger.info(`  Created ${catResult.length} product categories`)
    } catch (error: any) {
      logger.warn(`  Category creation error: ${error.message}`)
    }
  } else {
    logger.info("  All 27 categories already exist")
  }

  const { data: allCategories } = await query.graph({
    entity: "product_category",
    fields: ["id", "handle"],
  })
  const getCatId = (handle: string) => {
    const cat = (allCategories || []).find((c: any) => c.handle === handle)
    return cat?.id
  }

  const { data: existingProducts } = await query.graph({
    entity: "product",
    fields: ["id", "handle"],
  })
  const existingProductHandles = new Set((existingProducts || []).map((p: any) => p.handle))

  const img = (id: string, w = 800, h = 800) =>
    `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&q=80`
  const thumb = (id: string) => img(id, 400, 400)

  const allProducts = [
    {
      title: "Premium Saudi Bisht",
      handle: "premium-saudi-bisht",
      subtitle: "Traditional Saudi Cloak",
      description: "Luxurious hand-stitched Saudi bisht crafted from premium wool blend with gold thread embroidery. Perfect for formal occasions, weddings, and Eid celebrations. Made by master artisans in Al-Ahsa.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1594938298603-c8148c4dae35"),
      images: [
        { url: img("1594938298603-c8148c4dae35") },
        { url: img("1617137968427-85924c800a22") },
        { url: img("1490481651871-ab68de25d43d") },
      ],
      categories: [{ id: getCatId("fashion-apparel") }, { id: getCatId("traditional-clothing") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["M", "L", "XL", "XXL"] }],
      variants: [
        { title: "Medium", sku: "BISHT-M", manage_inventory: false, options: { Size: "M" }, prices: [{ amount: 120000, currency_code: "sar" }, { amount: 32000, currency_code: "usd" }] },
        { title: "Large", sku: "BISHT-L", manage_inventory: false, options: { Size: "L" }, prices: [{ amount: 120000, currency_code: "sar" }, { amount: 32000, currency_code: "usd" }] },
        { title: "X-Large", sku: "BISHT-XL", manage_inventory: false, options: { Size: "XL" }, prices: [{ amount: 130000, currency_code: "sar" }, { amount: 34700, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 800,
      origin_country: "sa",
    },
    {
      title: "Designer Abaya Collection",
      handle: "designer-abaya-collection",
      subtitle: "Modern Designer Abaya",
      description: "Contemporary abaya blending traditional modesty with modern fashion. Features intricate beadwork on sleeves and hem, crafted from flowing crepe fabric. Available in classic black and midnight navy.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1490114538077-0a7f8cb49891"),
      images: [
        { url: img("1490114538077-0a7f8cb49891") },
        { url: img("1509631179647-0177331693ae") },
        { url: img("1594938298603-c8148c4dae35") },
      ],
      categories: [{ id: getCatId("fashion-apparel") }, { id: getCatId("traditional-clothing") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["S", "M", "L"] }, { title: "Color", values: ["Black", "Navy"] }],
      variants: [
        { title: "Small / Black", sku: "ABAYA-S-BLK", manage_inventory: false, options: { Size: "S", Color: "Black" }, prices: [{ amount: 85000, currency_code: "sar" }, { amount: 22700, currency_code: "usd" }] },
        { title: "Medium / Black", sku: "ABAYA-M-BLK", manage_inventory: false, options: { Size: "M", Color: "Black" }, prices: [{ amount: 85000, currency_code: "sar" }, { amount: 22700, currency_code: "usd" }] },
        { title: "Large / Navy", sku: "ABAYA-L-NVY", manage_inventory: false, options: { Size: "L", Color: "Navy" }, prices: [{ amount: 89000, currency_code: "sar" }, { amount: 23700, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 500,
      origin_country: "sa",
    },
    {
      title: "Men's Premium Linen Suit",
      handle: "mens-premium-linen-suit",
      subtitle: "Summer Linen Suit",
      description: "Tailored linen suit designed for the Gulf climate. Lightweight breathable fabric keeps you cool in summer heat while maintaining a sharp, professional appearance. Italian-inspired cut with Middle Eastern tailoring.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1617137968427-85924c800a22"),
      images: [
        { url: img("1617137968427-85924c800a22") },
        { url: img("1490481651871-ab68de25d43d") },
        { url: img("1594938298603-c8148c4dae35") },
      ],
      categories: [{ id: getCatId("fashion-apparel") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["48", "50", "52", "54"] }],
      variants: [
        { title: "Size 48", sku: "LSUIT-48", manage_inventory: false, options: { Size: "48" }, prices: [{ amount: 240000, currency_code: "sar" }, { amount: 64000, currency_code: "usd" }] },
        { title: "Size 50", sku: "LSUIT-50", manage_inventory: false, options: { Size: "50" }, prices: [{ amount: 240000, currency_code: "sar" }, { amount: 64000, currency_code: "usd" }] },
        { title: "Size 52", sku: "LSUIT-52", manage_inventory: false, options: { Size: "52" }, prices: [{ amount: 250000, currency_code: "sar" }, { amount: 66700, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 1200,
      origin_country: "it",
    },
    {
      title: "Smart Home Hub Pro",
      handle: "smart-home-hub-pro",
      subtitle: "WiFi/Zigbee Smart Hub",
      description: "Central smart home controller supporting WiFi, Zigbee, and Z-Wave protocols. Compatible with over 500 devices from major brands. Features Arabic voice control and supports local processing for privacy.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1498049794561-7780e7231661"),
      images: [
        { url: img("1498049794561-7780e7231661") },
        { url: img("1519389950473-47ba0277781c") },
        { url: img("1505740420928-5e560c06d30e") },
      ],
      categories: [{ id: getCatId("electronics-gadgets") }].filter((c) => c.id),
      options: [{ title: "Model", values: ["Standard", "Pro"] }],
      variants: [
        { title: "Standard", sku: "SMHUB-STD", manage_inventory: false, options: { Model: "Standard" }, prices: [{ amount: 45000, currency_code: "sar" }, { amount: 12000, currency_code: "usd" }] },
        { title: "Pro", sku: "SMHUB-PRO", manage_inventory: false, options: { Model: "Pro" }, prices: [{ amount: 67500, currency_code: "sar" }, { amount: 18000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 350,
      origin_country: "cn",
    },
    {
      title: "4K Drone Camera",
      handle: "4k-drone-camera",
      subtitle: "Professional Aerial Photography Drone",
      description: "Advanced aerial drone with 4K HDR camera, 3-axis gimbal stabilization, and 45-minute flight time. Features GPS waypoint navigation and obstacle avoidance. Ideal for desert landscape photography.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1526738549149-8e07eca6c147"),
      images: [
        { url: img("1526738549149-8e07eca6c147") },
        { url: img("1550009158-9ebf69b0b7a0") },
        { url: img("1505740420928-5e560c06d30e") },
        { url: img("1498049794561-7780e7231661") },
      ],
      categories: [{ id: getCatId("electronics-gadgets") }].filter((c) => c.id),
      options: [{ title: "Bundle", values: ["Drone Only", "Fly More Kit"] }],
      variants: [
        { title: "Drone Only", sku: "DRONE-4K", manage_inventory: false, options: { Bundle: "Drone Only" }, prices: [{ amount: 320000, currency_code: "sar" }, { amount: 85300, currency_code: "usd" }] },
        { title: "Fly More Kit", sku: "DRONE-4K-KIT", manage_inventory: false, options: { Bundle: "Fly More Kit" }, prices: [{ amount: 420000, currency_code: "sar" }, { amount: 112000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 900,
      origin_country: "cn",
    },
    {
      title: "Arabic E-Reader",
      handle: "arabic-e-reader",
      subtitle: "RTL-Enabled E-Reader",
      description: "Purpose-built e-reader with native right-to-left Arabic text support and anti-glare display. Stores up to 10,000 books with built-in Arabic dictionary. Waterproof design perfect for poolside reading.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1519389950473-47ba0277781c"),
      images: [
        { url: img("1519389950473-47ba0277781c") },
        { url: img("1498049794561-7780e7231661") },
        { url: img("1505740420928-5e560c06d30e") },
      ],
      categories: [{ id: getCatId("electronics-gadgets") }, { id: getCatId("books-media") }].filter((c) => c.id),
      options: [{ title: "Storage", values: ["32GB", "64GB"] }],
      variants: [
        { title: "32GB", sku: "EREADER-32", manage_inventory: false, options: { Storage: "32GB" }, prices: [{ amount: 68000, currency_code: "sar" }, { amount: 18100, currency_code: "usd" }] },
        { title: "64GB", sku: "EREADER-64", manage_inventory: false, options: { Storage: "64GB" }, prices: [{ amount: 82000, currency_code: "sar" }, { amount: 21900, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 200,
      origin_country: "cn",
    },
    {
      title: "Majlis Seating Set",
      handle: "majlis-seating-set",
      subtitle: "Traditional Floor Seating",
      description: "Complete majlis seating set including floor cushions, back rests, and bolster pillows. Upholstered in premium brocade fabric with traditional Arabian geometric patterns. Seats 8-10 guests comfortably.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1555041469-a586c61ea9bc"),
      images: [
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1586023492125-27b2c045efd7") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1560448204-e02f11c3d0e2") },
      ],
      categories: [{ id: getCatId("home-living") }, { id: getCatId("saudi-specialties") }].filter((c) => c.id),
      options: [{ title: "Color", values: ["Burgundy", "Gold", "Green"] }],
      variants: [
        { title: "Burgundy", sku: "MAJLIS-BUR", manage_inventory: false, options: { Color: "Burgundy" }, prices: [{ amount: 450000, currency_code: "sar" }, { amount: 120000, currency_code: "usd" }] },
        { title: "Gold", sku: "MAJLIS-GLD", manage_inventory: false, options: { Color: "Gold" }, prices: [{ amount: 470000, currency_code: "sar" }, { amount: 125300, currency_code: "usd" }] },
        { title: "Green", sku: "MAJLIS-GRN", manage_inventory: false, options: { Color: "Green" }, prices: [{ amount: 450000, currency_code: "sar" }, { amount: 120000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 25000,
      origin_country: "sa",
    },
    {
      title: "Arabian Brass Lamp",
      handle: "arabian-brass-lamp",
      subtitle: "Handcrafted Decorative Lamp",
      description: "Exquisite hand-pierced brass lamp casting intricate shadow patterns. Inspired by traditional Arabian lantern designs with modern LED compatibility. Each piece is uniquely crafted by skilled metalworkers.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1586023492125-27b2c045efd7"),
      images: [
        { url: img("1586023492125-27b2c045efd7") },
        { url: img("1618221195710-dd6b41faaea6") },
        { url: img("1555041469-a586c61ea9bc") },
      ],
      categories: [{ id: getCatId("home-living") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["Small", "Medium", "Large"] }],
      variants: [
        { title: "Small", sku: "LAMP-BR-S", manage_inventory: false, options: { Size: "Small" }, prices: [{ amount: 28000, currency_code: "sar" }, { amount: 7500, currency_code: "usd" }] },
        { title: "Medium", sku: "LAMP-BR-M", manage_inventory: false, options: { Size: "Medium" }, prices: [{ amount: 38000, currency_code: "sar" }, { amount: 10100, currency_code: "usd" }] },
        { title: "Large", sku: "LAMP-BR-L", manage_inventory: false, options: { Size: "Large" }, prices: [{ amount: 52000, currency_code: "sar" }, { amount: 13900, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 2500,
      origin_country: "ma",
    },
    {
      title: "Prayer Mat Deluxe",
      handle: "prayer-mat-deluxe",
      subtitle: "Premium Embroidered Prayer Mat",
      description: "Luxurious velvet prayer mat with hand-embroidered mihrab design and memory foam padding. Features a built-in compass and comes in a premium gift box. Perfect for daily prayers or as a meaningful gift.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1560448204-e02f11c3d0e2"),
      images: [
        { url: img("1560448204-e02f11c3d0e2") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1618221195710-dd6b41faaea6") },
      ],
      categories: [{ id: getCatId("home-living") }, { id: getCatId("saudi-specialties") }].filter((c) => c.id),
      options: [{ title: "Color", values: ["Green", "Blue", "Burgundy"] }],
      variants: [
        { title: "Green", sku: "PMAT-GRN", manage_inventory: false, options: { Color: "Green" }, prices: [{ amount: 22000, currency_code: "sar" }, { amount: 5900, currency_code: "usd" }] },
        { title: "Blue", sku: "PMAT-BLU", manage_inventory: false, options: { Color: "Blue" }, prices: [{ amount: 22000, currency_code: "sar" }, { amount: 5900, currency_code: "usd" }] },
        { title: "Burgundy", sku: "PMAT-BUR", manage_inventory: false, options: { Color: "Burgundy" }, prices: [{ amount: 24000, currency_code: "sar" }, { amount: 6400, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 1000,
      origin_country: "tr",
    },
    {
      title: "Ajwa Dates Gift Box",
      handle: "ajwa-dates-gift-box",
      subtitle: "1kg Premium Ajwa Dates",
      description: "Hand-selected premium Ajwa dates from Al-Madinah Al-Munawwarah, known for their rich dark color and soft texture. Packed in an elegant wooden gift box with gold detailing. The finest quality for gifting.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1504674900247-0877df9cc836"),
      images: [
        { url: img("1504674900247-0877df9cc836") },
        { url: img("1563729784474-d77dbb933a9e") },
        { url: img("1509042239860-f550ce710b93") },
      ],
      categories: [{ id: getCatId("food-beverages-rich") }, { id: getCatId("saudi-specialties") }].filter((c) => c.id),
      options: [{ title: "Weight", values: ["500g", "1kg", "2kg"] }],
      variants: [
        { title: "500g", sku: "AJWA-500", manage_inventory: false, options: { Weight: "500g" }, prices: [{ amount: 10000, currency_code: "sar" }, { amount: 2700, currency_code: "usd" }] },
        { title: "1kg", sku: "AJWA-1KG", manage_inventory: false, options: { Weight: "1kg" }, prices: [{ amount: 18000, currency_code: "sar" }, { amount: 4800, currency_code: "usd" }] },
        { title: "2kg", sku: "AJWA-2KG", manage_inventory: false, options: { Weight: "2kg" }, prices: [{ amount: 32000, currency_code: "sar" }, { amount: 8500, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 1200,
      origin_country: "sa",
    },
    {
      title: "Saudi Honey Collection",
      handle: "saudi-honey-collection",
      subtitle: "Sidr Honey Assortment",
      description: "Premium collection of three Yemeni Sidr honeys harvested from the Do'an Valley. Includes raw, creamed, and honeycomb varieties. Renowned for exceptional flavor and traditional medicinal properties.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1504674900247-0877df9cc836"),
      images: [
        { url: img("1504674900247-0877df9cc836") },
        { url: img("1473093295043-cdd812d0e601") },
        { url: img("1504674900247-0877df9cc836") },
      ],
      categories: [{ id: getCatId("food-beverages-rich") }].filter((c) => c.id),
      options: [{ title: "Set", values: ["Trio Set", "Premium Jar"] }],
      variants: [
        { title: "Trio Set", sku: "HONEY-TRIO", manage_inventory: false, options: { Set: "Trio Set" }, prices: [{ amount: 35000, currency_code: "sar" }, { amount: 9300, currency_code: "usd" }] },
        { title: "Premium Jar (500g)", sku: "HONEY-PREM", manage_inventory: false, options: { Set: "Premium Jar" }, prices: [{ amount: 22000, currency_code: "sar" }, { amount: 5900, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 1800,
      origin_country: "ye",
    },
    {
      title: "Arabic Coffee Set",
      handle: "arabic-coffee-set-dallah",
      subtitle: "Dallah with Finjan Cups",
      description: "Traditional Arabic coffee set featuring a polished brass Dallah (coffee pot) with six hand-painted finjan cups. The set includes premium Saudi green coffee beans and cardamom. Perfect for hospitality.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1509042239860-f550ce710b93"),
      images: [
        { url: img("1509042239860-f550ce710b93") },
        { url: img("1563729784474-d77dbb933a9e") },
        { url: img("1473093295043-cdd812d0e601") },
        { url: img("1504674900247-0877df9cc836") },
      ],
      categories: [{ id: getCatId("food-beverages-rich") }, { id: getCatId("saudi-specialties") }].filter((c) => c.id),
      options: [{ title: "Finish", values: ["Brass", "Silver"] }],
      variants: [
        { title: "Brass Finish", sku: "DALLAH-BRS", manage_inventory: false, options: { Finish: "Brass" }, prices: [{ amount: 29000, currency_code: "sar" }, { amount: 7700, currency_code: "usd" }] },
        { title: "Silver Finish", sku: "DALLAH-SLV", manage_inventory: false, options: { Finish: "Silver" }, prices: [{ amount: 39000, currency_code: "sar" }, { amount: 10400, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 2200,
      origin_country: "sa",
    },
    {
      title: "Dead Sea Mud Mask",
      handle: "dead-sea-mud-mask",
      subtitle: "Natural Mineral Face Mask",
      description: "Pure Dead Sea mud enriched with 26 essential minerals for deep skin detoxification. Draws out impurities while nourishing skin with magnesium, calcium, and potassium. Suitable for all skin types.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1556228578-8c89e6adf883"),
      images: [
        { url: img("1556228578-8c89e6adf883") },
        { url: img("1608248543803-ba4f8c70ae0b") },
        { url: img("1608248543803-ba4f8c70ae0b") },
      ],
      categories: [{ id: getCatId("health-beauty") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["200g", "500g"] }],
      variants: [
        { title: "200g", sku: "DSMASK-200", manage_inventory: false, options: { Size: "200g" }, prices: [{ amount: 12000, currency_code: "sar" }, { amount: 3200, currency_code: "usd" }] },
        { title: "500g", sku: "DSMASK-500", manage_inventory: false, options: { Size: "500g" }, prices: [{ amount: 22000, currency_code: "sar" }, { amount: 5900, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 550,
      origin_country: "jo",
    },
    {
      title: "Argan Oil Set",
      handle: "argan-oil-set",
      subtitle: "Pure Cold-Pressed Argan Oil",
      description: "100% pure cold-pressed argan oil from Morocco, triple-filtered for maximum purity. Set includes hair treatment oil, face serum, and body moisturizer. Rich in Vitamin E and essential fatty acids.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1556228578-8c89e6adf883"),
      images: [
        { url: img("1556228578-8c89e6adf883") },
        { url: img("1570172619-7b44c2e0e9db") },
        { url: img("1608248543803-ba4f8c70ae0b") },
      ],
      categories: [{ id: getCatId("health-beauty") }].filter((c) => c.id),
      options: [{ title: "Type", values: ["Hair Oil", "Face Serum", "Complete Set"] }],
      variants: [
        { title: "Hair Oil (100ml)", sku: "ARGAN-HAIR", manage_inventory: false, options: { Type: "Hair Oil" }, prices: [{ amount: 8500, currency_code: "sar" }, { amount: 2300, currency_code: "usd" }] },
        { title: "Face Serum (30ml)", sku: "ARGAN-FACE", manage_inventory: false, options: { Type: "Face Serum" }, prices: [{ amount: 9500, currency_code: "sar" }, { amount: 2500, currency_code: "usd" }] },
        { title: "Complete Set", sku: "ARGAN-SET", manage_inventory: false, options: { Type: "Complete Set" }, prices: [{ amount: 16500, currency_code: "sar" }, { amount: 4400, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 400,
      origin_country: "ma",
    },
    {
      title: "Black Seed Oil Premium",
      handle: "black-seed-oil-premium",
      subtitle: "Organic Nigella Sativa",
      description: "Certified organic cold-pressed black seed oil (Nigella sativa) from Ethiopian highlands. Known as Habbatus Sauda, this superfood is prized in Islamic tradition. First cold-press extraction preserves nutrients.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1608248543803-ba4f8c70ae0b"),
      images: [
        { url: img("1608248543803-ba4f8c70ae0b") },
        { url: img("1556228578-8c89e6adf883") },
        { url: img("1570172619-7b44c2e0e9db") },
      ],
      categories: [{ id: getCatId("health-beauty") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["100ml", "250ml"] }],
      variants: [
        { title: "100ml", sku: "BSEED-100", manage_inventory: false, options: { Size: "100ml" }, prices: [{ amount: 9500, currency_code: "sar" }, { amount: 2500, currency_code: "usd" }] },
        { title: "250ml", sku: "BSEED-250", manage_inventory: false, options: { Size: "250ml" }, prices: [{ amount: 18000, currency_code: "sar" }, { amount: 4800, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 300,
      origin_country: "et",
    },
    {
      title: "Car Window Tint Kit",
      handle: "car-window-tint-kit",
      subtitle: "UV Protection Film",
      description: "Professional-grade ceramic window tint film providing 99% UV rejection. Specially designed for the intense Gulf sun to protect interior and keep vehicles cool. Includes all tools for DIY installation.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1494976388531-d1058494cdd8"),
      images: [
        { url: img("1494976388531-d1058494cdd8") },
        { url: img("1503376780353-7e6692767b70") },
        { url: img("1503376780353-7e6692767b70") },
      ],
      categories: [{ id: getCatId("automotive-parts") }].filter((c) => c.id),
      options: [{ title: "Shade", values: ["Light (35%)", "Medium (20%)", "Dark (5%)"] }],
      variants: [
        { title: "Light (35%)", sku: "TINT-35", manage_inventory: false, options: { Shade: "Light (35%)" }, prices: [{ amount: 25000, currency_code: "sar" }, { amount: 6700, currency_code: "usd" }] },
        { title: "Medium (20%)", sku: "TINT-20", manage_inventory: false, options: { Shade: "Medium (20%)" }, prices: [{ amount: 25000, currency_code: "sar" }, { amount: 6700, currency_code: "usd" }] },
        { title: "Dark (5%)", sku: "TINT-05", manage_inventory: false, options: { Shade: "Dark (5%)" }, prices: [{ amount: 28000, currency_code: "sar" }, { amount: 7500, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 800,
      origin_country: "us",
    },
    {
      title: "Desert Rally Kit",
      handle: "desert-rally-kit",
      subtitle: "Off-Road Accessories",
      description: "Complete desert rally preparation kit for off-road adventures in the Empty Quarter. Includes sand recovery boards, deflation gauge, heavy-duty tow strap, and LED light bar. Essential for Saudi desert driving.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1494976388531-d1058494cdd8"),
      images: [
        { url: img("1494976388531-d1058494cdd8") },
        { url: img("1549317661-bd32e8ce0a6c") },
        { url: img("1494976388531-d1058494cdd8") },
        { url: img("1503376780353-7e6692767b70") },
      ],
      categories: [{ id: getCatId("automotive-parts") }, { id: getCatId("sports-fitness") }].filter((c) => c.id),
      options: [{ title: "Kit", values: ["Basic", "Pro"] }],
      variants: [
        { title: "Basic Kit", sku: "RALLY-BASIC", manage_inventory: false, options: { Kit: "Basic" }, prices: [{ amount: 180000, currency_code: "sar" }, { amount: 48000, currency_code: "usd" }] },
        { title: "Pro Kit", sku: "RALLY-PRO", manage_inventory: false, options: { Kit: "Pro" }, prices: [{ amount: 280000, currency_code: "sar" }, { amount: 74700, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 12000,
      origin_country: "au",
    },
    {
      title: "Premium Dashcam 4K",
      handle: "premium-dashcam-4k",
      subtitle: "Front & Rear Camera",
      description: "Dual-channel 4K dashcam with front and rear cameras, GPS logging, and parking mode. Heat-resistant design rated for 70°C dashboard temperatures. Features Arabic menu and supports Saudi date formats.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1503376780353-7e6692767b70"),
      images: [
        { url: img("1503376780353-7e6692767b70") },
        { url: img("1549317661-bd32e8ce0a6c") },
        { url: img("1494976388531-d1058494cdd8") },
      ],
      categories: [{ id: getCatId("automotive-parts") }, { id: getCatId("electronics-gadgets") }].filter((c) => c.id),
      options: [{ title: "Model", values: ["Front Only", "Front + Rear"] }],
      variants: [
        { title: "Front Only", sku: "DASH-FRONT", manage_inventory: false, options: { Model: "Front Only" }, prices: [{ amount: 38000, currency_code: "sar" }, { amount: 10100, currency_code: "usd" }] },
        { title: "Front + Rear", sku: "DASH-DUAL", manage_inventory: false, options: { Model: "Front + Rear" }, prices: [{ amount: 58000, currency_code: "sar" }, { amount: 15500, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 250,
      origin_country: "kr",
    },
    {
      title: "Royal Oud Mukhallat",
      handle: "royal-oud-mukhallat",
      subtitle: "Premium Oud Blend",
      description: "An exquisite blend of aged Cambodian oud with Indian sandalwood, Turkish rose, and Yemeni amber. This mukhallat represents the pinnacle of Arabian perfumery. Aged for 12 months in traditional wooden casks.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1588405748880-12d1d2a59f75"),
      images: [
        { url: img("1588405748880-12d1d2a59f75") },
        { url: img("1587017539504-67cfbddac569") },
        { url: img("1527903789411-89ce8cbbdd1e") },
        { url: img("1587017539504-67cfbddac569") },
      ],
      categories: [{ id: getCatId("oud-perfumes") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["6ml", "12ml", "25ml"] }],
      variants: [
        { title: "6ml Attar", sku: "OUD-ROYAL-6", manage_inventory: false, options: { Size: "6ml" }, prices: [{ amount: 45000, currency_code: "sar" }, { amount: 12000, currency_code: "usd" }] },
        { title: "12ml Attar", sku: "OUD-ROYAL-12", manage_inventory: false, options: { Size: "12ml" }, prices: [{ amount: 89000, currency_code: "sar" }, { amount: 23700, currency_code: "usd" }] },
        { title: "25ml Attar", sku: "OUD-ROYAL-25", manage_inventory: false, options: { Size: "25ml" }, prices: [{ amount: 165000, currency_code: "sar" }, { amount: 44000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 100,
      origin_country: "sa",
    },
    {
      title: "Bakhoor Collection",
      handle: "bakhoor-collection",
      subtitle: "6 Wood Chip Varieties",
      description: "Curated collection of six premium bakhoor varieties including Oud Al-Hindi, Sandalwood Rose, Amber Musk, Jasmine Oud, White Oud, and Royal Blend. Each variety comes in a handcrafted ceramic container.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1587017539504-67cfbddac569"),
      images: [
        { url: img("1587017539504-67cfbddac569") },
        { url: img("1588405748880-12d1d2a59f75") },
        { url: img("1588405748880-12d1d2a59f75") },
      ],
      categories: [{ id: getCatId("oud-perfumes") }, { id: getCatId("saudi-specialties") }].filter((c) => c.id),
      options: [{ title: "Set", values: ["6-Piece Set", "3-Piece Sampler"] }],
      variants: [
        { title: "6-Piece Set", sku: "BAKH-6", manage_inventory: false, options: { Set: "6-Piece Set" }, prices: [{ amount: 34000, currency_code: "sar" }, { amount: 9100, currency_code: "usd" }] },
        { title: "3-Piece Sampler", sku: "BAKH-3", manage_inventory: false, options: { Set: "3-Piece Sampler" }, prices: [{ amount: 18000, currency_code: "sar" }, { amount: 4800, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 600,
      origin_country: "sa",
    },
    {
      title: "Musk Al Tahara",
      handle: "musk-al-tahara",
      subtitle: "Traditional Musk Perfume",
      description: "Pure white musk perfume oil prized for its clean, fresh scent. A staple in Arabian homes, traditionally used after ablution. Long-lasting fragrance with subtle powdery and floral notes.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1587017539504-67cfbddac569"),
      images: [
        { url: img("1587017539504-67cfbddac569") },
        { url: img("1527903789411-89ce8cbbdd1e") },
        { url: img("1588405748880-12d1d2a59f75") },
      ],
      categories: [{ id: getCatId("oud-perfumes") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["25ml", "50ml"] }],
      variants: [
        { title: "25ml", sku: "MUSK-25", manage_inventory: false, options: { Size: "25ml" }, prices: [{ amount: 15000, currency_code: "sar" }, { amount: 4000, currency_code: "usd" }] },
        { title: "50ml", sku: "MUSK-50", manage_inventory: false, options: { Size: "50ml" }, prices: [{ amount: 25000, currency_code: "sar" }, { amount: 6700, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 80,
      origin_country: "sa",
    },
    {
      title: "Amber Oud Intense",
      handle: "amber-oud-intense",
      subtitle: "Concentrated Attar",
      description: "Rich concentrated attar combining aged amber resin with premium oud oil. This intense fragrance unfolds over hours, revealing warm spicy notes followed by deep woody undertones. A true connoisseur's choice.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1588405748880-12d1d2a59f75"),
      images: [
        { url: img("1588405748880-12d1d2a59f75") },
        { url: img("1588405748880-12d1d2a59f75") },
        { url: img("1527903789411-89ce8cbbdd1e") },
      ],
      categories: [{ id: getCatId("oud-perfumes") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["3ml", "6ml", "12ml"] }],
      variants: [
        { title: "3ml", sku: "AMBER-3", manage_inventory: false, options: { Size: "3ml" }, prices: [{ amount: 32000, currency_code: "sar" }, { amount: 8500, currency_code: "usd" }] },
        { title: "6ml", sku: "AMBER-6", manage_inventory: false, options: { Size: "6ml" }, prices: [{ amount: 65000, currency_code: "sar" }, { amount: 17300, currency_code: "usd" }] },
        { title: "12ml", sku: "AMBER-12", manage_inventory: false, options: { Size: "12ml" }, prices: [{ amount: 120000, currency_code: "sar" }, { amount: 32000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 50,
      origin_country: "sa",
    },
    {
      title: "Gold Arabic Calligraphy Necklace",
      handle: "gold-arabic-calligraphy-necklace",
      subtitle: "18K Gold Custom Necklace",
      description: "Stunning 18K gold pendant featuring your name or phrase in elegant Arabic Thuluth calligraphy. Handcrafted by master jewelers in the Riyadh Gold Souk. Comes with a 45cm Italian gold chain.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1515562141207-7a88fb7ce338"),
      images: [
        { url: img("1515562141207-7a88fb7ce338") },
        { url: img("1599643478518-a784e5dc4c8f") },
        { url: img("1602751584552-8a5a5e9d3940") },
      ],
      categories: [{ id: getCatId("jewelry-watches") }].filter((c) => c.id),
      options: [{ title: "Metal", values: ["Yellow Gold", "White Gold", "Rose Gold"] }],
      variants: [
        { title: "Yellow Gold", sku: "NECK-YG", manage_inventory: false, options: { Metal: "Yellow Gold" }, prices: [{ amount: 280000, currency_code: "sar" }, { amount: 74700, currency_code: "usd" }] },
        { title: "White Gold", sku: "NECK-WG", manage_inventory: false, options: { Metal: "White Gold" }, prices: [{ amount: 295000, currency_code: "sar" }, { amount: 78700, currency_code: "usd" }] },
        { title: "Rose Gold", sku: "NECK-RG", manage_inventory: false, options: { Metal: "Rose Gold" }, prices: [{ amount: 290000, currency_code: "sar" }, { amount: 77300, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 15,
      origin_country: "sa",
    },
    {
      title: "Diamond Solitaire Ring",
      handle: "diamond-solitaire-ring",
      subtitle: "1ct Diamond Engagement Ring",
      description: "Classic solitaire engagement ring featuring a GIA-certified 1-carat round brilliant diamond set in platinum. D-E color, VVS1-VVS2 clarity. Includes international grading certificate and luxury box.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1515562141207-7a88fb7ce338"),
      images: [
        { url: img("1515562141207-7a88fb7ce338") },
        { url: img("1617038260897-41a1f14a8ca6") },
        { url: img("1602751584552-8a5a5e9d3940") },
      ],
      categories: [{ id: getCatId("jewelry-watches") }].filter((c) => c.id),
      options: [{ title: "Ring Size", values: ["6", "7", "8", "9"] }],
      variants: [
        { title: "Size 6", sku: "DRING-6", manage_inventory: false, options: { "Ring Size": "6" }, prices: [{ amount: 1500000, currency_code: "sar" }, { amount: 400000, currency_code: "usd" }] },
        { title: "Size 7", sku: "DRING-7", manage_inventory: false, options: { "Ring Size": "7" }, prices: [{ amount: 1500000, currency_code: "sar" }, { amount: 400000, currency_code: "usd" }] },
        { title: "Size 8", sku: "DRING-8", manage_inventory: false, options: { "Ring Size": "8" }, prices: [{ amount: 1500000, currency_code: "sar" }, { amount: 400000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 8,
      origin_country: "be",
    },
    {
      title: "Men's Luxury Watch",
      handle: "mens-luxury-watch-swiss",
      subtitle: "Swiss Automatic Movement",
      description: "Premium Swiss-made automatic watch with 42mm case in brushed stainless steel. Features sapphire crystal, Arabic numeral dial, and 100m water resistance. Exhibition caseback reveals the decorated movement.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1599643478518-a784e5dc4c8f"),
      images: [
        { url: img("1599643478518-a784e5dc4c8f") },
        { url: img("1515562141207-7a88fb7ce338") },
        { url: img("1617038260897-41a1f14a8ca6") },
      ],
      categories: [{ id: getCatId("jewelry-watches") }].filter((c) => c.id),
      options: [{ title: "Strap", values: ["Steel Bracelet", "Leather Strap"] }],
      variants: [
        { title: "Steel Bracelet", sku: "WATCH-STL", manage_inventory: false, options: { Strap: "Steel Bracelet" }, prices: [{ amount: 420000, currency_code: "sar" }, { amount: 112000, currency_code: "usd" }] },
        { title: "Leather Strap", sku: "WATCH-LTH", manage_inventory: false, options: { Strap: "Leather Strap" }, prices: [{ amount: 390000, currency_code: "sar" }, { amount: 104000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 180,
      origin_country: "ch",
    },
    {
      title: "Handwoven Sadu Cushion",
      handle: "handwoven-sadu-cushion",
      subtitle: "Bedouin Pattern Cushion",
      description: "Authentic Sadu-weave cushion handmade by Bedouin artisans using traditional techniques. Features geometric patterns in vibrant desert colors. Each piece is unique and takes weeks to complete.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1555041469-a586c61ea9bc"),
      images: [
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1618221195710-dd6b41faaea6") },
      ],
      categories: [{ id: getCatId("saudi-specialties") }, { id: getCatId("arts-crafts") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["40x40cm", "60x60cm"] }],
      variants: [
        { title: "40x40cm", sku: "SADU-40", manage_inventory: false, options: { Size: "40x40cm" }, prices: [{ amount: 18000, currency_code: "sar" }, { amount: 4800, currency_code: "usd" }] },
        { title: "60x60cm", sku: "SADU-60", manage_inventory: false, options: { Size: "60x60cm" }, prices: [{ amount: 28000, currency_code: "sar" }, { amount: 7500, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 600,
      origin_country: "sa",
    },
    {
      title: "Silver Khanjar Dagger",
      handle: "silver-khanjar-dagger",
      subtitle: "Decorative Heritage Piece",
      description: "Ornamental silver khanjar dagger with intricate filigree work and semi-precious stone inlays. A cherished symbol of Arabian heritage, perfect as a display piece or collector's item. Comes with wooden display stand.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1618221195710-dd6b41faaea6"),
      images: [
        { url: img("1618221195710-dd6b41faaea6") },
        { url: img("1586023492125-27b2c045efd7") },
        { url: img("1560448204-e02f11c3d0e2") },
      ],
      categories: [{ id: getCatId("saudi-specialties") }, { id: getCatId("arts-crafts") }].filter((c) => c.id),
      options: [{ title: "Style", values: ["Classic", "Royal"] }],
      variants: [
        { title: "Classic", sku: "KHANJAR-CLS", manage_inventory: false, options: { Style: "Classic" }, prices: [{ amount: 95000, currency_code: "sar" }, { amount: 25300, currency_code: "usd" }] },
        { title: "Royal Edition", sku: "KHANJAR-RYL", manage_inventory: false, options: { Style: "Royal" }, prices: [{ amount: 185000, currency_code: "sar" }, { amount: 49300, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 450,
      origin_country: "om",
    },
    {
      title: "Camel Leather Bag",
      handle: "camel-leather-bag",
      subtitle: "Artisan Crafted Handbag",
      description: "Handcrafted messenger bag made from genuine camel leather, tanned using traditional methods. Features brass hardware and adjustable strap. Ages beautifully with use, developing a rich patina over time.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1490481651871-ab68de25d43d"),
      images: [
        { url: img("1490481651871-ab68de25d43d") },
        { url: img("1490114538077-0a7f8cb49891") },
        { url: img("1509631179647-0177331693ae") },
      ],
      categories: [{ id: getCatId("saudi-specialties") }, { id: getCatId("fashion-apparel") }].filter((c) => c.id),
      options: [{ title: "Color", values: ["Natural Tan", "Dark Brown"] }],
      variants: [
        { title: "Natural Tan", sku: "CLTHR-TAN", manage_inventory: false, options: { Color: "Natural Tan" }, prices: [{ amount: 42000, currency_code: "sar" }, { amount: 11200, currency_code: "usd" }] },
        { title: "Dark Brown", sku: "CLTHR-BRN", manage_inventory: false, options: { Color: "Dark Brown" }, prices: [{ amount: 42000, currency_code: "sar" }, { amount: 11200, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 700,
      origin_country: "sa",
    },
    {
      title: "Palm Weaving Art",
      handle: "palm-weaving-art",
      subtitle: "Framed Wall Art",
      description: "Beautiful framed wall art featuring traditional Saudi palm leaf weaving in a contemporary frame. Created by artisans from Al-Ahsa oasis using date palm fronds. A stunning blend of heritage and modern decor.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1555041469-a586c61ea9bc"),
      images: [
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1586023492125-27b2c045efd7") },
      ],
      categories: [{ id: getCatId("saudi-specialties") }, { id: getCatId("arts-crafts") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["30x30cm", "50x50cm"] }],
      variants: [
        { title: "30x30cm", sku: "PALM-30", manage_inventory: false, options: { Size: "30x30cm" }, prices: [{ amount: 28000, currency_code: "sar" }, { amount: 7500, currency_code: "usd" }] },
        { title: "50x50cm", sku: "PALM-50", manage_inventory: false, options: { Size: "50x50cm" }, prices: [{ amount: 45000, currency_code: "sar" }, { amount: 12000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 1200,
      origin_country: "sa",
    },
    {
      title: "Kids Arabic Alphabet Set",
      handle: "kids-arabic-alphabet-set",
      subtitle: "Educational Toy Set",
      description: "Colorful wooden Arabic alphabet blocks with matching picture cards. Each letter features an animal or object illustration to aid learning. Non-toxic paint, smooth edges, and comes in a sturdy storage box.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1503454537195-1dcabb73ffb9"),
      images: [
        { url: img("1503454537195-1dcabb73ffb9") },
        { url: img("1515488042361-ee00e0ddd4e4") },
        { url: img("1503454537195-1dcabb73ffb9") },
      ],
      categories: [{ id: getCatId("children-baby") }, { id: getCatId("education-training") }].filter((c) => c.id),
      options: [{ title: "Type", values: ["Wooden Blocks", "Magnetic Letters"] }],
      variants: [
        { title: "Wooden Blocks", sku: "ALPHA-WOOD", manage_inventory: false, options: { Type: "Wooden Blocks" }, prices: [{ amount: 12000, currency_code: "sar" }, { amount: 3200, currency_code: "usd" }] },
        { title: "Magnetic Letters", sku: "ALPHA-MAG", manage_inventory: false, options: { Type: "Magnetic Letters" }, prices: [{ amount: 8500, currency_code: "sar" }, { amount: 2300, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 800,
      origin_country: "cn",
    },
    {
      title: "Baby Thobe Set",
      handle: "baby-thobe-set",
      subtitle: "Infant Traditional Wear",
      description: "Adorable baby thobe set in soft organic cotton with matching ghutra headpiece. Features snap buttons for easy dressing and gentle elastic waistband. Perfect for Eid celebrations and family gatherings.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1515488042361-ee00e0ddd4e4"),
      images: [
        { url: img("1515488042361-ee00e0ddd4e4") },
        { url: img("1581783898-cc3d3d5a684c") },
        { url: img("1515488042361-ee00e0ddd4e4") },
      ],
      categories: [{ id: getCatId("children-baby") }, { id: getCatId("traditional-clothing") }].filter((c) => c.id),
      options: [{ title: "Age", values: ["0-6m", "6-12m", "12-24m"] }],
      variants: [
        { title: "0-6 months", sku: "BTHOBE-06", manage_inventory: false, options: { Age: "0-6m" }, prices: [{ amount: 8500, currency_code: "sar" }, { amount: 2300, currency_code: "usd" }] },
        { title: "6-12 months", sku: "BTHOBE-12", manage_inventory: false, options: { Age: "6-12m" }, prices: [{ amount: 8500, currency_code: "sar" }, { amount: 2300, currency_code: "usd" }] },
        { title: "12-24 months", sku: "BTHOBE-24", manage_inventory: false, options: { Age: "12-24m" }, prices: [{ amount: 9500, currency_code: "sar" }, { amount: 2500, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 200,
      origin_country: "sa",
    },
    {
      title: "Islamic Stories Book Set",
      handle: "islamic-stories-book-set",
      subtitle: "10-Book Collection",
      description: "Beautiful illustrated collection of 10 Islamic stories for children ages 4-10. Features stories of the Prophets with colorful artwork. Bilingual Arabic-English text helps children learn both languages.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1503454537195-1dcabb73ffb9"),
      images: [
        { url: img("1503454537195-1dcabb73ffb9") },
        { url: img("1503454537195-1dcabb73ffb9") },
        { url: img("1581783898-cc3d3d5a684c") },
      ],
      categories: [{ id: getCatId("children-baby") }, { id: getCatId("books-media") }].filter((c) => c.id),
      options: [{ title: "Language", values: ["Arabic Only", "Bilingual AR/EN"] }],
      variants: [
        { title: "Arabic Only", sku: "ISTORY-AR", manage_inventory: false, options: { Language: "Arabic Only" }, prices: [{ amount: 15000, currency_code: "sar" }, { amount: 4000, currency_code: "usd" }] },
        { title: "Bilingual AR/EN", sku: "ISTORY-BI", manage_inventory: false, options: { Language: "Bilingual AR/EN" }, prices: [{ amount: 18000, currency_code: "sar" }, { amount: 4800, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 1500,
      origin_country: "lb",
    },
    {
      title: "Arabic Calligraphy Course",
      handle: "arabic-calligraphy-course",
      subtitle: "Online Video Course",
      description: "Comprehensive 40-hour online course teaching traditional Arabic calligraphy from basics to mastery. Covers Naskh, Thuluth, and Diwani scripts. Includes practice worksheets, video lessons, and instructor feedback.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1503454537195-1dcabb73ffb9"),
      images: [
        { url: img("1503454537195-1dcabb73ffb9") },
        { url: img("1519389950473-47ba0277781c") },
        { url: img("1498049794561-7780e7231661") },
      ],
      categories: [{ id: getCatId("digital-products") }, { id: getCatId("education-training") }].filter((c) => c.id),
      options: [{ title: "Access", values: ["3 Months", "Lifetime"] }],
      variants: [
        { title: "3-Month Access", sku: "CALLI-3M", manage_inventory: false, options: { Access: "3 Months" }, prices: [{ amount: 19900, currency_code: "sar" }, { amount: 5300, currency_code: "usd" }] },
        { title: "Lifetime Access", sku: "CALLI-LIFE", manage_inventory: false, options: { Access: "Lifetime" }, prices: [{ amount: 39900, currency_code: "sar" }, { amount: 10600, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 0,
    },
    {
      title: "Quran Recitation App License",
      handle: "quran-recitation-app-license",
      subtitle: "Annual Subscription",
      description: "Premium Quran recitation app with word-by-word pronunciation, multiple reciters, and interactive tajweed rules. Includes translation in 40+ languages, bookmarking, and offline access for Hajj and Umrah travel.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1519389950473-47ba0277781c"),
      images: [
        { url: img("1519389950473-47ba0277781c") },
        { url: img("1505740420928-5e560c06d30e") },
        { url: img("1498049794561-7780e7231661") },
      ],
      categories: [{ id: getCatId("digital-products") }].filter((c) => c.id),
      options: [{ title: "Plan", values: ["Annual", "Lifetime"] }],
      variants: [
        { title: "Annual", sku: "QURAN-ANN", manage_inventory: false, options: { Plan: "Annual" }, prices: [{ amount: 4900, currency_code: "sar" }, { amount: 1300, currency_code: "usd" }] },
        { title: "Lifetime", sku: "QURAN-LIFE", manage_inventory: false, options: { Plan: "Lifetime" }, prices: [{ amount: 14900, currency_code: "sar" }, { amount: 4000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 0,
    },
    {
      title: "Saudi Business Template Pack",
      handle: "saudi-business-template-pack",
      subtitle: "PPT/Word Templates",
      description: "Professional business template pack featuring Saudi Vision 2030 themes, bilingual Arabic-English layouts, and corporate designs. Includes 50 PowerPoint slides, 20 Word documents, and 10 Excel financial models.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1505740420928-5e560c06d30e"),
      images: [
        { url: img("1505740420928-5e560c06d30e") },
        { url: img("1526738549149-8e07eca6c147") },
        { url: img("1498049794561-7780e7231661") },
      ],
      categories: [{ id: getCatId("digital-products") }, { id: getCatId("office-business") }].filter((c) => c.id),
      options: [{ title: "Format", values: ["Full Pack", "PowerPoint Only"] }],
      variants: [
        { title: "Full Pack", sku: "TMPL-FULL", manage_inventory: false, options: { Format: "Full Pack" }, prices: [{ amount: 7900, currency_code: "sar" }, { amount: 2100, currency_code: "usd" }] },
        { title: "PowerPoint Only", sku: "TMPL-PPT", manage_inventory: false, options: { Format: "PowerPoint Only" }, prices: [{ amount: 4900, currency_code: "sar" }, { amount: 1300, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 0,
    },
    {
      title: "Desert Running Shoes",
      handle: "desert-running-shoes",
      subtitle: "Heat-Resistant Athletic Shoes",
      description: "Engineered for hot climate running with breathable mesh upper and heat-resistant outsole rated to 65°C. Features sand-proof construction and reflective elements for early morning desert runs in Riyadh.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1461896836934-ffe607ba8211"),
      images: [
        { url: img("1461896836934-ffe607ba8211") },
        { url: img("1526676037777-05a232554f77") },
        { url: img("1552674605-db6ffd4facb5") },
      ],
      categories: [{ id: getCatId("sports-fitness") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["41", "42", "43", "44", "45"] }],
      variants: [
        { title: "Size 42", sku: "DRUN-42", manage_inventory: false, options: { Size: "42" }, prices: [{ amount: 52000, currency_code: "sar" }, { amount: 13900, currency_code: "usd" }] },
        { title: "Size 43", sku: "DRUN-43", manage_inventory: false, options: { Size: "43" }, prices: [{ amount: 52000, currency_code: "sar" }, { amount: 13900, currency_code: "usd" }] },
        { title: "Size 44", sku: "DRUN-44", manage_inventory: false, options: { Size: "44" }, prices: [{ amount: 52000, currency_code: "sar" }, { amount: 13900, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 350,
      origin_country: "de",
    },
    {
      title: "Falcon Training Glove",
      handle: "falcon-training-glove",
      subtitle: "Professional Falconry Glove",
      description: "Professional-grade falconry glove crafted from triple-layered buffalo leather. Designed for the Saudi falconry tradition with reinforced wrist protection and swivel ring attachment. Used by champion falconers.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1552674605-db6ffd4facb5"),
      images: [
        { url: img("1552674605-db6ffd4facb5") },
        { url: img("1517649763962-0c623066013b") },
        { url: img("1526676037777-05a232554f77") },
      ],
      categories: [{ id: getCatId("sports-fitness") }, { id: getCatId("saudi-specialties") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["Medium", "Large", "X-Large"] }],
      variants: [
        { title: "Medium", sku: "FALCON-M", manage_inventory: false, options: { Size: "Medium" }, prices: [{ amount: 68000, currency_code: "sar" }, { amount: 18100, currency_code: "usd" }] },
        { title: "Large", sku: "FALCON-L", manage_inventory: false, options: { Size: "Large" }, prices: [{ amount: 68000, currency_code: "sar" }, { amount: 18100, currency_code: "usd" }] },
        { title: "X-Large", sku: "FALCON-XL", manage_inventory: false, options: { Size: "X-Large" }, prices: [{ amount: 72000, currency_code: "sar" }, { amount: 19200, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 400,
      origin_country: "pk",
    },
    {
      title: "Beach Volleyball Pro Set",
      handle: "beach-volleyball-pro-set",
      subtitle: "Net and Balls",
      description: "Tournament-quality beach volleyball set with regulation net, boundary lines, and two official match balls. Quick-setup design perfect for Red Sea coast and NEOM beach activities. UV-resistant materials.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1552674605-db6ffd4facb5"),
      images: [
        { url: img("1552674605-db6ffd4facb5") },
        { url: img("1461896836934-ffe607ba8211") },
        { url: img("1517649763962-0c623066013b") },
      ],
      categories: [{ id: getCatId("sports-fitness") }].filter((c) => c.id),
      options: [{ title: "Set", values: ["Standard", "Tournament"] }],
      variants: [
        { title: "Standard Set", sku: "VBALL-STD", manage_inventory: false, options: { Set: "Standard" }, prices: [{ amount: 34000, currency_code: "sar" }, { amount: 9100, currency_code: "usd" }] },
        { title: "Tournament Set", sku: "VBALL-TOUR", manage_inventory: false, options: { Set: "Tournament" }, prices: [{ amount: 52000, currency_code: "sar" }, { amount: 13900, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 5000,
      origin_country: "cn",
    },
    {
      title: "Date Palm Seedling Kit",
      handle: "date-palm-seedling-kit",
      subtitle: "3 Varieties Kit",
      description: "Grow your own date palms with this starter kit featuring three premium Saudi varieties: Ajwa, Sukkari, and Khalas. Includes specialized soil mix, fertilizer, and detailed growing guide for Gulf climate.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1560448204-e02f11c3d0e2"),
      images: [
        { url: img("1560448204-e02f11c3d0e2") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1618221195710-dd6b41faaea6") },
      ],
      categories: [{ id: getCatId("garden-outdoor") }].filter((c) => c.id),
      options: [{ title: "Kit", values: ["3-Variety Kit", "Single Variety"] }],
      variants: [
        { title: "3-Variety Kit", sku: "PALM-3VAR", manage_inventory: false, options: { Kit: "3-Variety Kit" }, prices: [{ amount: 19500, currency_code: "sar" }, { amount: 5200, currency_code: "usd" }] },
        { title: "Single Variety (Ajwa)", sku: "PALM-AJWA", manage_inventory: false, options: { Kit: "Single Variety" }, prices: [{ amount: 8500, currency_code: "sar" }, { amount: 2300, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 3000,
      origin_country: "sa",
    },
    {
      title: "Desert Garden Collection",
      handle: "desert-garden-collection",
      subtitle: "Drought-Resistant Plants",
      description: "Curated collection of 8 drought-resistant plants perfect for Saudi gardens. Includes native succulents, desert rose, and Arabian jasmine. Each plant is nursery-grown and acclimatized to Gulf temperatures.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1618221195710-dd6b41faaea6"),
      images: [
        { url: img("1618221195710-dd6b41faaea6") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1560448204-e02f11c3d0e2") },
      ],
      categories: [{ id: getCatId("garden-outdoor") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["Starter", "Established"] }],
      variants: [
        { title: "Starter Collection", sku: "DGARDEN-S", manage_inventory: false, options: { Size: "Starter" }, prices: [{ amount: 28000, currency_code: "sar" }, { amount: 7500, currency_code: "usd" }] },
        { title: "Established Collection", sku: "DGARDEN-E", manage_inventory: false, options: { Size: "Established" }, prices: [{ amount: 48000, currency_code: "sar" }, { amount: 12800, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 8000,
      origin_country: "sa",
    },
    {
      title: "Outdoor Arabian Tent",
      handle: "outdoor-arabian-tent",
      subtitle: "4-Person Glamping Tent",
      description: "Luxurious Arabian-style glamping tent with traditional peaked roof design. Made from heavy-duty canvas with UV protection. Features mesh windows, roll-up door, and ground sheet. Perfect for desert camping.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1586023492125-27b2c045efd7"),
      images: [
        { url: img("1586023492125-27b2c045efd7") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1560448204-e02f11c3d0e2") },
      ],
      categories: [{ id: getCatId("garden-outdoor") }, { id: getCatId("travel-tourism") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["4-Person", "8-Person"] }],
      variants: [
        { title: "4-Person", sku: "TENT-4P", manage_inventory: false, options: { Size: "4-Person" }, prices: [{ amount: 360000, currency_code: "sar" }, { amount: 96000, currency_code: "usd" }] },
        { title: "8-Person", sku: "TENT-8P", manage_inventory: false, options: { Size: "8-Person" }, prices: [{ amount: 580000, currency_code: "sar" }, { amount: 154700, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 18000,
      origin_country: "cn",
    },
    {
      title: "Hajj & Umrah Travel Kit",
      handle: "hajj-umrah-travel-kit",
      subtitle: "Complete Pilgrimage Essentials",
      description: "All-in-one travel kit for Hajj and Umrah pilgrims. Includes ihram towels, prayer mat, dua book, unscented toiletries, portable bidet, and waist pouch. TSA-approved packing in a durable carry bag.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1504674900247-0877df9cc836"),
      images: [
        { url: img("1504674900247-0877df9cc836") },
        { url: img("1560448204-e02f11c3d0e2") },
        { url: img("1563729784474-d77dbb933a9e") },
      ],
      categories: [{ id: getCatId("travel-tourism") }, { id: getCatId("saudi-specialties") }].filter((c) => c.id),
      options: [{ title: "Type", values: ["Men's Kit", "Women's Kit"] }],
      variants: [
        { title: "Men's Kit", sku: "HAJJ-MEN", manage_inventory: false, options: { Type: "Men's Kit" }, prices: [{ amount: 24000, currency_code: "sar" }, { amount: 6400, currency_code: "usd" }] },
        { title: "Women's Kit", sku: "HAJJ-WMN", manage_inventory: false, options: { Type: "Women's Kit" }, prices: [{ amount: 22000, currency_code: "sar" }, { amount: 5900, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 2500,
      origin_country: "sa",
    },
    {
      title: "Pet Falcon Accessories Kit",
      handle: "pet-falcon-accessories-kit",
      subtitle: "Premium Falconry Gear",
      description: "Complete falcon care kit including leather hood, jesses, swivel, leash, and portable perch. Crafted from premium materials by experienced falconry artisans. Suitable for Saker and Peregrine falcons.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1517649763962-0c623066013b"),
      images: [
        { url: img("1517649763962-0c623066013b") },
        { url: img("1552674605-db6ffd4facb5") },
        { url: img("1526676037777-05a232554f77") },
      ],
      categories: [{ id: getCatId("pets-animals") }, { id: getCatId("saudi-specialties") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["Medium Bird", "Large Bird"] }],
      variants: [
        { title: "Medium Bird Kit", sku: "FKIT-MED", manage_inventory: false, options: { Size: "Medium Bird" }, prices: [{ amount: 85000, currency_code: "sar" }, { amount: 22700, currency_code: "usd" }] },
        { title: "Large Bird Kit", sku: "FKIT-LRG", manage_inventory: false, options: { Size: "Large Bird" }, prices: [{ amount: 105000, currency_code: "sar" }, { amount: 28000, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 1200,
      origin_country: "pk",
    },
    {
      title: "Legal Document Template Suite",
      handle: "legal-document-template-suite",
      subtitle: "Saudi Commercial Law Templates",
      description: "Comprehensive suite of 30+ legal document templates compliant with Saudi commercial law. Includes employment contracts, NDAs, partnership agreements, and company formation docs. Bilingual Arabic-English.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1505740420928-5e560c06d30e"),
      images: [
        { url: img("1505740420928-5e560c06d30e") },
        { url: img("1519389950473-47ba0277781c") },
        { url: img("1498049794561-7780e7231661") },
      ],
      categories: [{ id: getCatId("legal-services") }, { id: getCatId("digital-products") }].filter((c) => c.id),
      options: [{ title: "Package", values: ["Starter", "Professional"] }],
      variants: [
        { title: "Starter (10 templates)", sku: "LEGAL-START", manage_inventory: false, options: { Package: "Starter" }, prices: [{ amount: 29900, currency_code: "sar" }, { amount: 8000, currency_code: "usd" }] },
        { title: "Professional (30+ templates)", sku: "LEGAL-PRO", manage_inventory: false, options: { Package: "Professional" }, prices: [{ amount: 69900, currency_code: "sar" }, { amount: 18600, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 0,
    },
    {
      title: "Financial Planning Toolkit",
      handle: "financial-planning-toolkit",
      subtitle: "Saudi Investment Guide",
      description: "Digital financial planning toolkit designed for Saudi investors. Includes investment calculators, Shariah-compliant fund screener, zakat calculator, and retirement planning worksheets aligned with GOSI regulations.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1526738549149-8e07eca6c147"),
      images: [
        { url: img("1526738549149-8e07eca6c147") },
        { url: img("1505740420928-5e560c06d30e") },
        { url: img("1550009158-9ebf69b0b7a0") },
      ],
      categories: [{ id: getCatId("financial-services") }, { id: getCatId("digital-products") }].filter((c) => c.id),
      options: [{ title: "Plan", values: ["Basic", "Premium"] }],
      variants: [
        { title: "Basic", sku: "FINPLAN-B", manage_inventory: false, options: { Plan: "Basic" }, prices: [{ amount: 14900, currency_code: "sar" }, { amount: 4000, currency_code: "usd" }] },
        { title: "Premium", sku: "FINPLAN-P", manage_inventory: false, options: { Plan: "Premium" }, prices: [{ amount: 34900, currency_code: "sar" }, { amount: 9300, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 0,
    },
    {
      title: "Premium Office Chair",
      handle: "premium-office-chair-ergonomic",
      subtitle: "Ergonomic Desk Chair",
      description: "High-end ergonomic office chair designed for long Saudi work days. Features mesh back for ventilation in AC environments, lumbar support, and adjustable armrests. BIFMA certified for 150kg capacity.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1586023492125-27b2c045efd7"),
      images: [
        { url: img("1586023492125-27b2c045efd7") },
        { url: img("1555041469-a586c61ea9bc") },
        { url: img("1555041469-a586c61ea9bc") },
      ],
      categories: [{ id: getCatId("office-business") }].filter((c) => c.id),
      options: [{ title: "Color", values: ["Black", "Gray"] }],
      variants: [
        { title: "Black", sku: "OCHAIR-BLK", manage_inventory: false, options: { Color: "Black" }, prices: [{ amount: 189000, currency_code: "sar" }, { amount: 50400, currency_code: "usd" }] },
        { title: "Gray", sku: "OCHAIR-GRY", manage_inventory: false, options: { Color: "Gray" }, prices: [{ amount: 189000, currency_code: "sar" }, { amount: 50400, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 18000,
      origin_country: "cn",
    },
    {
      title: "Restaurant Dining Voucher",
      handle: "restaurant-dining-voucher",
      subtitle: "Premium Dining Experience",
      description: "Gift voucher for a premium dining experience at top-rated Riyadh restaurants. Valid at 50+ partner restaurants across the Kingdom. Includes appetizer, main course, dessert, and Arabic coffee service.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1563729784474-d77dbb933a9e"),
      images: [
        { url: img("1563729784474-d77dbb933a9e") },
        { url: img("1473093295043-cdd812d0e601") },
        { url: img("1509042239860-f550ce710b93") },
      ],
      categories: [{ id: getCatId("restaurant-dining") }].filter((c) => c.id),
      options: [{ title: "Value", values: ["SAR 200", "SAR 500", "SAR 1000"] }],
      variants: [
        { title: "SAR 200 Voucher", sku: "DINE-200", manage_inventory: false, options: { Value: "SAR 200" }, prices: [{ amount: 20000, currency_code: "sar" }, { amount: 5300, currency_code: "usd" }] },
        { title: "SAR 500 Voucher", sku: "DINE-500", manage_inventory: false, options: { Value: "SAR 500" }, prices: [{ amount: 50000, currency_code: "sar" }, { amount: 13300, currency_code: "usd" }] },
        { title: "SAR 1000 Voucher", sku: "DINE-1000", manage_inventory: false, options: { Value: "SAR 1000" }, prices: [{ amount: 100000, currency_code: "sar" }, { amount: 26700, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 0,
    },
    {
      title: "Fresh Grocery Box",
      handle: "fresh-grocery-box-weekly",
      subtitle: "Weekly Fresh Produce Box",
      description: "Weekly subscription box of farm-fresh fruits and vegetables sourced from local Saudi farms. Includes seasonal produce, herbs, and salad greens. Delivered chilled to your door every Sunday morning.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1473093295043-cdd812d0e601"),
      images: [
        { url: img("1473093295043-cdd812d0e601") },
        { url: img("1504674900247-0877df9cc836") },
        { url: img("1504674900247-0877df9cc836") },
      ],
      categories: [{ id: getCatId("grocery-fresh") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["Small (2 people)", "Large (4-6 people)"] }],
      variants: [
        { title: "Small Box", sku: "GROC-SM", manage_inventory: false, options: { Size: "Small (2 people)" }, prices: [{ amount: 12000, currency_code: "sar" }, { amount: 3200, currency_code: "usd" }] },
        { title: "Large Box", sku: "GROC-LG", manage_inventory: false, options: { Size: "Large (4-6 people)" }, prices: [{ amount: 22000, currency_code: "sar" }, { amount: 5900, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 5000,
      origin_country: "sa",
    },
    {
      title: "Healthcare First Aid Kit",
      handle: "healthcare-first-aid-kit-pro",
      subtitle: "Professional Medical Kit",
      description: "Comprehensive first aid kit meeting Saudi Red Crescent standards. Contains 150+ medical supplies including trauma dressings, splints, CPR mask, and medications. Ideal for homes, offices, and desert trips.",
      status: "published",
      is_giftcard: false,
      thumbnail: thumb("1608248543803-ba4f8c70ae0b"),
      images: [
        { url: img("1608248543803-ba4f8c70ae0b") },
        { url: img("1556228578-8c89e6adf883") },
        { url: img("1608248543803-ba4f8c70ae0b") },
      ],
      categories: [{ id: getCatId("healthcare-medical") }].filter((c) => c.id),
      options: [{ title: "Size", values: ["Home Kit", "Professional Kit"] }],
      variants: [
        { title: "Home Kit (75 items)", sku: "FAID-HOME", manage_inventory: false, options: { Size: "Home Kit" }, prices: [{ amount: 18000, currency_code: "sar" }, { amount: 4800, currency_code: "usd" }] },
        { title: "Professional Kit (150+ items)", sku: "FAID-PRO", manage_inventory: false, options: { Size: "Professional Kit" }, prices: [{ amount: 35000, currency_code: "sar" }, { amount: 9300, currency_code: "usd" }] },
      ],
      sales_channels: channelIds,
      weight: 3000,
      origin_country: "de",
    },
  ]

  const productsToCreate = allProducts.filter((p) => !existingProductHandles.has(p.handle))

  if (productsToCreate.length === 0) {
    logger.info("  All rich products already exist, skipping creation")
  } else {
    logger.info(`  Creating ${productsToCreate.length} rich products (skipping ${allProducts.length - productsToCreate.length} existing)...`)

    const batchSize = 5
    let created = 0

    for (let i = 0; i < productsToCreate.length; i += batchSize) {
      const batch = productsToCreate.slice(i, i + batchSize)
      try {
        await createProductsWorkflow(container).run({
          input: { products: batch },
        })
        created += batch.length
        logger.info(`  Batch ${Math.floor(i / batchSize) + 1}: Created ${batch.length} products (${created}/${productsToCreate.length})`)
      } catch (error: any) {
        logger.warn(`  Batch ${Math.floor(i / batchSize) + 1} error: ${error.message}`)
        for (const product of batch) {
          try {
            await createProductsWorkflow(container).run({
              input: { products: [product] },
            })
            created++
            logger.info(`    Retry success: ${product.title}`)
          } catch (retryError: any) {
            logger.warn(`    Failed: ${product.title} - ${retryError.message}`)
          }
        }
      }
    }

    logger.info(`  Successfully created ${created} products`)
  }

  logger.info("")
  logger.info("========================================")
  logger.info("Rich Product Seed Complete!")
  logger.info(`  Total products defined: ${allProducts.length}`)
  logger.info(`  Categories: 27 verticals`)
  logger.info("========================================")
}
