import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http";
import { handleApiError } from "../../../../lib/api-error-handler";

const SEED_DATA = [
  { id: "nl-1", name: "Tech Trends Weekly", topic: "technology", thumbnail: "/seed-images/newsletters/1518770660439-4636190af475.jpg", edition_date: "2026-02-10", topics_covered: ["AI & Machine Learning", "Web3 Updates", "Cloud Computing"], description: "Stay ahead with the latest technology trends, product launches, and industry insights.", topics: ["Artificial Intelligence", "Cloud Computing", "Cybersecurity", "Software Development"], testimonials: [{ name: "Ahmed K.", quote: "The best tech newsletter I've subscribed to. Always relevant and insightful.", role: "CTO" }, { name: "Sara M.", quote: "Keeps me updated on industry trends without overwhelming my inbox.", role: "Software Engineer" }, { name: "Omar R.", quote: "A must-read for anyone in tech. Concise and actionable.", role: "Product Manager" }], sampleContent: [{ title: "The Rise of AI Agents in Enterprise", excerpt: "How autonomous AI agents are transforming business workflows and decision-making processes.", date: "2026-02-10" }, { title: "Cloud Cost Optimization Strategies for 2026", excerpt: "Practical tips to reduce your cloud spending without sacrificing performance.", date: "2026-02-03" }, { title: "Web3 Security: Lessons from Recent Breaches", excerpt: "Analyzing the biggest Web3 security incidents and what developers can learn.", date: "2026-01-27" }], reviews: [{ author: "Tariq M.", rating: 5, comment: "The most comprehensive tech newsletter I've found. Saves me hours of research.", created_at: "2025-01-10T09:00:00Z" }, { author: "Lina A.", rating: 4, comment: "Well-curated content that's actually relevant to my daily work.", created_at: "2025-01-20T14:00:00Z" }, { author: "Faisal R.", rating: 5, comment: "Love the deep dives into AI topics. Always learn something new.", created_at: "2025-02-01T10:00:00Z" }, { author: "Nadia H.", rating: 4, comment: "Concise and actionable. Perfect length for my morning commute read.", created_at: "2025-02-10T08:00:00Z" }, { author: "Badr S.", rating: 5, comment: "Been subscribed for a year and it keeps getting better with each edition.", created_at: "2025-02-20T12:00:00Z" }] },
  { id: "nl-2", name: "Style & Living", topic: "lifestyle", thumbnail: "/seed-images/newsletters/1489987707025-afc232f7ea0f.jpg", edition_date: "2026-02-08", topics_covered: ["Fashion Tips", "Interior Design", "Wellness"], description: "Your weekly guide to fashion, home design, and modern living.", topics: ["Fashion Trends", "Home Decor", "Wellness Tips", "Travel Inspiration"], testimonials: [{ name: "Layla H.", quote: "Love the curated style picks every week. My go-to for inspiration!", role: "Fashion Blogger" }, { name: "Fatima A.", quote: "Beautiful layouts and genuinely useful lifestyle advice.", role: "Interior Designer" }, { name: "Nadia S.", quote: "The wellness section alone is worth subscribing for.", role: "Reader" }], sampleContent: [{ title: "Spring 2026 Color Palette Preview", excerpt: "The trending colors that will dominate fashion and interiors this spring.", date: "2026-02-08" }, { title: "Minimalist Home Office Makeover", excerpt: "Transform your workspace with these elegant and functional design ideas.", date: "2026-02-01" }, { title: "Morning Routines of Successful Creatives", excerpt: "How top designers and artists start their day for maximum inspiration.", date: "2026-01-25" }], reviews: [{ author: "Mona K.", rating: 5, comment: "This newsletter transformed my approach to home styling. Beautiful content!", created_at: "2025-01-08T10:00:00Z" }, { author: "Yara D.", rating: 4, comment: "The fashion picks are always on-trend and affordable.", created_at: "2025-01-18T13:00:00Z" }, { author: "Huda W.", rating: 5, comment: "I look forward to every edition. The interior design tips are gold.", created_at: "2025-02-02T09:00:00Z" }, { author: "Salim J.", rating: 4, comment: "Great wellness advice that's practical and easy to follow.", created_at: "2025-02-12T15:00:00Z" }, { author: "Reem N.", rating: 5, comment: "Best lifestyle newsletter out there. Beautifully designed too.", created_at: "2025-02-22T11:00:00Z" }] },
  { id: "nl-3", name: "Business Insider Report", topic: "business", thumbnail: "/seed-images/content/1460925895917-afdab827c52f.jpg", edition_date: "2026-02-12", topics_covered: ["Market Analysis", "Startup News", "Investment Tips"], description: "Comprehensive business intelligence and market analysis for professionals.", topics: ["Market Analysis", "Startup Ecosystem", "Investment Strategies", "Leadership Insights"], testimonials: [{ name: "Khalid W.", quote: "Essential reading for business leaders. The market analysis is top-notch.", role: "CEO" }, { name: "Badr T.", quote: "Helped me make better investment decisions consistently.", role: "Investor" }, { name: "Reem D.", quote: "The startup coverage is unmatched. Great for founders.", role: "Entrepreneur" }], sampleContent: [{ title: "Q1 2026 Market Outlook: What Investors Should Know", excerpt: "Key market trends and investment opportunities for the first quarter.", date: "2026-02-12" }, { title: "Top 10 Startups to Watch in the MENA Region", excerpt: "Emerging companies disrupting industries across the Middle East and North Africa.", date: "2026-02-05" }, { title: "Leadership in the Age of Remote Work", excerpt: "How top executives are adapting their management styles for distributed teams.", date: "2026-01-29" }], reviews: [{ author: "Waleed G.", rating: 5, comment: "The market analysis alone is worth more than any paid subscription.", created_at: "2025-01-05T08:00:00Z" }, { author: "Amira B.", rating: 4, comment: "Actionable investment tips that have genuinely improved my portfolio.", created_at: "2025-01-15T11:00:00Z" }, { author: "Majid F.", rating: 5, comment: "Best business newsletter for MENA professionals. Essential reading.", created_at: "2025-02-03T10:00:00Z" }, { author: "Dina S.", rating: 4, comment: "The startup coverage helps me stay ahead of industry trends.", created_at: "2025-02-13T14:00:00Z" }, { author: "Hassan L.", rating: 5, comment: "Consistently high-quality content. My Monday morning must-read.", created_at: "2025-02-23T09:00:00Z" }] },
  { id: "nl-4", name: "Green Planet Digest", topic: "sustainability", thumbnail: "/seed-images/newsletters/1441974231531-c6227db76b6e.jpg", edition_date: "2026-02-05", topics_covered: ["Climate Action", "Sustainable Products", "Eco-Innovations"], description: "Environmental news, sustainable living tips, and eco-friendly product reviews.", topics: ["Climate Change", "Renewable Energy", "Sustainable Living", "Eco-Friendly Products"], testimonials: [{ name: "Huda J.", quote: "Changed my perspective on sustainable living. Highly recommend!", role: "Environmental Activist" }, { name: "Faisal B.", quote: "Great product reviews that help me make eco-conscious choices.", role: "Reader" }, { name: "Mona K.", quote: "The climate action updates keep me informed and motivated.", role: "Researcher" }], sampleContent: [{ title: "Solar Energy Breakthroughs in 2026", excerpt: "New solar technologies making renewable energy more accessible than ever.", date: "2026-02-05" }, { title: "Zero-Waste Kitchen: A Practical Guide", excerpt: "Simple swaps and habits to drastically reduce food waste at home.", date: "2026-01-29" }, { title: "The True Cost of Fast Fashion", excerpt: "How your clothing choices impact the environment and what alternatives exist.", date: "2026-01-22" }], reviews: [{ author: "Noura T.", rating: 5, comment: "This newsletter inspired me to make meaningful changes in my daily life.", created_at: "2025-01-07T09:00:00Z" }, { author: "Omar Q.", rating: 4, comment: "The eco-product reviews are unbiased and very helpful for shopping decisions.", created_at: "2025-01-17T12:00:00Z" }, { author: "Salwa E.", rating: 5, comment: "Finally a sustainability newsletter that's hopeful, not just doom and gloom.", created_at: "2025-02-04T10:00:00Z" }, { author: "Karim P.", rating: 4, comment: "Great resources for anyone starting their sustainability journey.", created_at: "2025-02-14T16:00:00Z" }, { author: "Layla V.", rating: 5, comment: "The climate action updates keep me informed and motivated to do more.", created_at: "2025-02-24T08:00:00Z" }] },
  { id: "nl-5", name: "Health & Wellness Focus", topic: "health", thumbnail: "/seed-images/bundles/1571019613454-1cb2f99b2d8b.jpg", edition_date: "2026-02-11", topics_covered: ["Nutrition Guide", "Fitness Plans", "Mental Health"], description: "Expert-backed health advice, workout routines, and nutrition guides.", topics: ["Nutrition Science", "Fitness Training", "Mental Health", "Preventive Care"], testimonials: [{ name: "Youssef N.", quote: "The nutrition guides are science-backed and easy to follow.", role: "Nutritionist" }, { name: "Amira L.", quote: "Helped me build a sustainable fitness routine. Love it!", role: "Fitness Enthusiast" }, { name: "Tariq F.", quote: "The mental health section is thoughtful and much needed.", role: "Psychologist" }], sampleContent: [{ title: "Mediterranean Diet: Science-Backed Benefits", excerpt: "Why researchers continue to recommend the Mediterranean diet for longevity.", date: "2026-02-11" }, { title: "Home Workout Plans That Actually Work", excerpt: "Effective exercise routines you can do with minimal equipment.", date: "2026-02-04" }, { title: "Managing Stress in a Hyperconnected World", excerpt: "Practical strategies for digital detox and mental wellness.", date: "2026-01-28" }], reviews: [{ author: "Fatima Z.", rating: 5, comment: "The nutrition guides changed my eating habits for the better. Science-based and clear.", created_at: "2025-01-09T08:00:00Z" }, { author: "Ziad M.", rating: 4, comment: "Workout plans are realistic and achievable. Not just for gym rats.", created_at: "2025-01-19T14:00:00Z" }, { author: "Ghada A.", rating: 5, comment: "The mental health articles are thoughtful and genuinely helpful.", created_at: "2025-02-05T10:00:00Z" }, { author: "Mansour H.", rating: 4, comment: "Well-researched content that I trust for my family's health decisions.", created_at: "2025-02-15T12:00:00Z" }, { author: "Rana K.", rating: 5, comment: "Best health newsletter I've subscribed to. Expert content without the jargon.", created_at: "2025-02-25T09:00:00Z" }] },
];

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  try {
    const notifService = req.scope.resolve("notificationPreferences") as any;
    const { id } = req.params;
    const item = await notifService.retrieveNotificationPreference(id);
    if (!item) {
      const seedItem = SEED_DATA.find(i => i.id === id) || SEED_DATA[0];
      return res.json({ item: seedItem });
    }
    return res.json({ item });
  } catch (error: any) {
    const { id } = req.params;
    const seedItem = SEED_DATA.find(i => i.id === id) || SEED_DATA[0];
    return res.json({ item: seedItem });
  }
}

// DELETE /store/newsletters/:id — unsubscribe
export async function DELETE(req: MedusaRequest, res: MedusaResponse) {
  try {
    const notifService = req.scope.resolve("notificationPreferences") as any;
    const { id } = req.params;
    await notifService.updatePreference({
      id,
      enabled: false,
    });
    return res.json({ success: true, message: "Unsubscribed successfully" });
  } catch (error: any) {
    handleApiError(res, error, "DELETE store newsletters id");
  }
}
