import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"


const SEED_DATA = [
  {
    id: "auto_seed_1",
    tenant_id: "default",
    seller_id: "seller_1",
    listing_type: "sale",
    title: "2024 Toyota Land Cruiser",
    make: "Toyota",
    model_name: "Land Cruiser",
    year: 2024,
    mileage_km: 5200,
    fuel_type: "petrol",
    transmission: "automatic",
    body_type: "suv",
    color: "Pearl White",
    condition: "new",
    price: 28500000,
    currency_code: "SAR",
    description: "Brand new Toyota Land Cruiser with premium package, leather interior, and advanced safety features.",
    features: ["Adaptive Cruise Control", "360 Camera", "Premium Audio", "Heated Seats"],
    location_city: "Riyadh",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop", price: 28500000, currency: "SAR", location: "Riyadh, Saudi Arabia" },
    thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop",
  },
  {
    id: "auto_seed_2",
    tenant_id: "default",
    seller_id: "seller_2",
    listing_type: "sale",
    title: "2023 BMW X5 xDrive40i",
    make: "BMW",
    model_name: "X5",
    year: 2023,
    mileage_km: 18500,
    fuel_type: "petrol",
    transmission: "automatic",
    body_type: "suv",
    color: "Mineral White",
    condition: "certified_pre_owned",
    price: 22000000,
    currency_code: "SAR",
    description: "Certified pre-owned BMW X5 with M Sport package, panoramic sunroof, and Harman Kardon sound system.",
    features: ["M Sport Package", "Panoramic Sunroof", "Harman Kardon", "Head-Up Display"],
    location_city: "Jeddah",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop", price: 22000000, currency: "SAR", location: "Jeddah, Saudi Arabia" },
    thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop",
  },
  {
    id: "auto_seed_3",
    tenant_id: "default",
    seller_id: "seller_3",
    listing_type: "sale",
    title: "2024 Mercedes-Benz GLE 450",
    make: "Mercedes-Benz",
    model_name: "GLE 450",
    year: 2024,
    mileage_km: 2100,
    fuel_type: "hybrid",
    transmission: "automatic",
    body_type: "suv",
    color: "Obsidian Black",
    condition: "new",
    price: 32000000,
    currency_code: "SAR",
    description: "New Mercedes-Benz GLE 450 4MATIC with AMG Line, MBUX infotainment, and EQ Boost mild hybrid system.",
    features: ["AMG Line", "MBUX", "Burmester Audio", "Air Suspension"],
    location_city: "Dammam",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop", price: 32000000, currency: "SAR", location: "Dammam, Saudi Arabia" },
    thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop",
  },
  {
    id: "auto_seed_4",
    tenant_id: "default",
    seller_id: "seller_4",
    listing_type: "sale",
    title: "2023 Lexus ES 350 F Sport",
    make: "Lexus",
    model_name: "ES 350",
    year: 2023,
    mileage_km: 12000,
    fuel_type: "petrol",
    transmission: "automatic",
    body_type: "sedan",
    color: "Sonic Silver",
    condition: "certified_pre_owned",
    price: 16500000,
    currency_code: "SAR",
    description: "Lexus ES 350 F Sport with Mark Levinson audio, navigation, and advanced safety package.",
    features: ["F Sport Package", "Mark Levinson Audio", "Navigation", "Blind Spot Monitor"],
    location_city: "Riyadh",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop", price: 16500000, currency: "SAR", location: "Riyadh, Saudi Arabia" },
    thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop",
  },
  {
    id: "auto_seed_5",
    tenant_id: "default",
    seller_id: "seller_5",
    listing_type: "sale",
    title: "2024 Genesis G80 3.5T",
    make: "Genesis",
    model_name: "G80",
    year: 2024,
    mileage_km: 800,
    fuel_type: "petrol",
    transmission: "automatic",
    body_type: "sedan",
    color: "Vik Black",
    condition: "new",
    price: 19500000,
    currency_code: "SAR",
    description: "All-new Genesis G80 with 3.5L twin-turbo V6, Lexicon audio, and Genesis Connected Services.",
    features: ["Twin-Turbo V6", "Lexicon Audio", "Remote Smart Parking", "Highway Driving Assist"],
    location_city: "Jeddah",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop", price: 19500000, currency: "SAR", location: "Jeddah, Saudi Arabia" },
    thumbnail: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&h=600&fit=crop",
  },
]

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  try {
    const mod = req.scope.resolve("automotive") as any
    const { id } = req.params
    const item = await mod.retrieveVehicleListing(id)
    if (!item) {
      const seedItem = SEED_DATA.find((s) => s.id === id) || SEED_DATA[0]
      return res.json({ item: seedItem })
    }
    return res.json({ item })
  } catch (error: any) {
    const seedItem = SEED_DATA.find((s) => s.id === req.params.id) || SEED_DATA[0]
    return res.json({ item: seedItem })
  }
}
