import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"

const SEED_GIGS = [
  { id: "gig-1", title: "Professional Logo & Brand Identity Design", description: "I will create a unique, modern logo and complete brand identity package including color palette, typography, and brand guidelines. Deliverables include vector files (AI, EPS, SVG), PNG/JPG variations, a brand style guide document, and unlimited revisions until you're satisfied.", category: "Design", budget: 25000, currency_code: "usd", duration_days: 7, seller: { name: "Alex Rivera", rating: 4.9, completed_gigs: 234, avatar: "/seed-images/gigs%2F1498050108023-c5249f4df085.jpg", member_since: "2022-03-15", response_time: "1 hour" }, thumbnail: "/seed-images/gigs%2F1498050108023-c5249f4df085.jpg", skills: ["Logo Design", "Branding", "Illustrator", "Photoshop"], status: "active", packages: [{ name: "Basic", price: 15000, delivery_days: 5, revisions: 2, description: "1 logo concept with 2 revisions" }, { name: "Standard", price: 25000, delivery_days: 7, revisions: 5, description: "3 logo concepts with brand colors and fonts" }, { name: "Premium", price: 45000, delivery_days: 10, revisions: -1, description: "Full brand identity package with unlimited revisions" }], reviews: [{ author: "Sarah M.", rating: 5, comment: "Incredible work! Alex delivered exactly what I envisioned.", created_at: "2025-04-20T00:00:00Z" }, { author: "James K.", rating: 5, comment: "Fast turnaround and professional quality.", created_at: "2025-04-15T00:00:00Z" }, { author: "Lisa P.", rating: 4, comment: "Great designer, very responsive to feedback.", created_at: "2025-04-10T00:00:00Z" }], faq: [{ question: "What file formats will I receive?", answer: "AI, EPS, SVG, PNG, JPG, and PDF files." }, { question: "Do you offer revisions?", answer: "Yes, all packages include revisions. Premium has unlimited." }], created_at: "2025-05-01T10:00:00Z" },
  { id: "gig-2", title: "Full-Stack Web Application Development", description: "Build a responsive, scalable web application using React, Node.js, and PostgreSQL with modern best practices. Includes CI/CD setup, testing, documentation, and deployment assistance.", category: "Development", budget: 150000, currency_code: "usd", duration_days: 30, seller: { name: "Priya Sharma", rating: 4.8, completed_gigs: 156, avatar: "/seed-images/gigs%2F1461749280684-dccba630e2f6.jpg", member_since: "2021-08-20", response_time: "2 hours" }, thumbnail: "/seed-images/gigs%2F1461749280684-dccba630e2f6.jpg", skills: ["React", "Node.js", "PostgreSQL", "TypeScript", "Docker"], status: "active", packages: [{ name: "Basic", price: 80000, delivery_days: 14, revisions: 2, description: "Simple web app with 3-5 pages" }, { name: "Standard", price: 150000, delivery_days: 30, revisions: 5, description: "Full-stack app with auth, dashboard, and API" }, { name: "Premium", price: 300000, delivery_days: 45, revisions: -1, description: "Enterprise app with CI/CD, testing, and deployment" }], reviews: [{ author: "Mike T.", rating: 5, comment: "Priya built an amazing application. Very professional.", created_at: "2025-04-18T00:00:00Z" }, { author: "Anna R.", rating: 5, comment: "Excellent code quality and documentation.", created_at: "2025-04-12T00:00:00Z" }, { author: "David L.", rating: 4, comment: "Great developer, delivered on time.", created_at: "2025-04-05T00:00:00Z" }], faq: [{ question: "What technologies do you use?", answer: "React, Next.js, Node.js, PostgreSQL, Redis, Docker." }, { question: "Do you provide source code?", answer: "Yes, full source code with documentation is included." }], created_at: "2025-04-28T08:00:00Z" },
  { id: "gig-3", title: "SEO Optimization & Content Strategy", description: "Comprehensive SEO audit, keyword research, and 3-month content strategy to boost organic traffic and search rankings. Includes competitor analysis, on-page optimization, and monthly reporting.", category: "Marketing", budget: 50000, currency_code: "usd", duration_days: 14, seller: { name: "Jordan Lee", rating: 4.7, completed_gigs: 312, avatar: "/seed-images/gigs%2F1532094349884-543bc11b234d.jpg", member_since: "2020-11-05", response_time: "30 minutes" }, thumbnail: "/seed-images/gigs%2F1532094349884-543bc11b234d.jpg", skills: ["SEO", "Content Marketing", "Analytics", "Google Ads"], status: "active", packages: [{ name: "Basic", price: 25000, delivery_days: 7, revisions: 1, description: "SEO audit with keyword research report" }, { name: "Standard", price: 50000, delivery_days: 14, revisions: 3, description: "Full SEO audit + 3-month content strategy" }, { name: "Premium", price: 100000, delivery_days: 30, revisions: -1, description: "Complete SEO overhaul with monthly reporting" }], reviews: [{ author: "Rachel W.", rating: 5, comment: "Our traffic increased 150% in 3 months!", created_at: "2025-04-22T00:00:00Z" }, { author: "Tom B.", rating: 4, comment: "Very thorough analysis and actionable recommendations.", created_at: "2025-04-16T00:00:00Z" }, { author: "Nina S.", rating: 5, comment: "Jordan knows SEO inside and out.", created_at: "2025-04-08T00:00:00Z" }], faq: [{ question: "How long until I see results?", answer: "SEO results typically appear within 2-4 months." }, { question: "Do you work with all industries?", answer: "Yes, I've worked with 50+ industries." }], created_at: "2025-05-05T12:00:00Z" },
  { id: "gig-4", title: "Professional Video Editing & Post-Production", description: "High-quality video editing including color grading, sound design, motion graphics, and final delivery in 4K. Perfect for YouTube, social media, commercials, and corporate videos.", category: "Video", budget: 75000, currency_code: "usd", duration_days: 10, seller: { name: "Sam Nakamura", rating: 4.9, completed_gigs: 98, avatar: "/seed-images/gigs%2F1532629345422-7515f3d16bb6.jpg", member_since: "2023-01-10", response_time: "1 hour" }, thumbnail: "/seed-images/gigs%2F1532629345422-7515f3d16bb6.jpg", skills: ["Premiere Pro", "After Effects", "DaVinci Resolve", "Motion Graphics"], status: "active", packages: [{ name: "Basic", price: 30000, delivery_days: 5, revisions: 2, description: "Basic editing up to 10 minutes" }, { name: "Standard", price: 75000, delivery_days: 10, revisions: 4, description: "Full editing with color grading and sound" }, { name: "Premium", price: 150000, delivery_days: 15, revisions: -1, description: "Premium editing with motion graphics and 4K" }], reviews: [{ author: "Chris A.", rating: 5, comment: "Sam's editing transformed our raw footage into art.", created_at: "2025-04-25T00:00:00Z" }, { author: "Emily F.", rating: 5, comment: "Stunning color grading and perfect pacing.", created_at: "2025-04-19T00:00:00Z" }, { author: "Mark H.", rating: 4, comment: "Great communicator and talented editor.", created_at: "2025-04-11T00:00:00Z" }], faq: [{ question: "What formats do you deliver in?", answer: "MP4, MOV, ProRes, or any format you need." }, { question: "Can you add subtitles?", answer: "Yes, both hardcoded and SRT subtitle files." }], created_at: "2025-05-03T15:30:00Z" },
  { id: "gig-5", title: "Mobile App UI/UX Design", description: "Design intuitive, beautiful mobile app interfaces with user research, wireframes, prototypes, and final Figma deliverables. Covering iOS, Android, and cross-platform design systems.", category: "Design", budget: 80000, currency_code: "usd", duration_days: 14, seller: { name: "Elena Costa", rating: 4.8, completed_gigs: 187, avatar: "/seed-images/gigs%2F1574717024653-61fd2cf4d44d.jpg", member_since: "2022-06-01", response_time: "45 minutes" }, thumbnail: "/seed-images/gigs%2F1574717024653-61fd2cf4d44d.jpg", skills: ["Figma", "UI Design", "User Research", "Prototyping"], status: "active", packages: [{ name: "Basic", price: 40000, delivery_days: 7, revisions: 2, description: "5 screens with basic wireframes" }, { name: "Standard", price: 80000, delivery_days: 14, revisions: 5, description: "10 screens with high-fidelity mockups" }, { name: "Premium", price: 160000, delivery_days: 21, revisions: -1, description: "Full app design system with prototype" }], reviews: [{ author: "Kevin Z.", rating: 5, comment: "Elena's designs are pixel-perfect and user-friendly.", created_at: "2025-04-23T00:00:00Z" }, { author: "Sophie L.", rating: 5, comment: "Amazing attention to detail and great communication.", created_at: "2025-04-17T00:00:00Z" }, { author: "Ryan P.", rating: 4, comment: "Beautiful designs delivered on schedule.", created_at: "2025-04-09T00:00:00Z" }], faq: [{ question: "Do you design for both iOS and Android?", answer: "Yes, I follow both Material Design and Apple HIG." }, { question: "What design tools do you use?", answer: "Primarily Figma, but also Sketch and Adobe XD." }], created_at: "2025-04-30T09:00:00Z" },
]

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  try {
    const freelanceService = req.scope.resolve("freelance") as any
    const { id } = req.params
    const item = await freelanceService.retrieveGig(id)
    if (!item) {
      const seed = SEED_GIGS.find(s => s.id === id) || SEED_GIGS[0]
      return res.json({ item: { ...seed, id } })
    }
    return res.json({ item })
  } catch (error: any) {
    const { id } = req.params
    const seed = SEED_GIGS.find(s => s.id === id) || SEED_GIGS[0]
    return res.json({ item: { ...seed, id } })
  }
}
