export type ModuleScope = "platform" | "tenant" | "shared"
export type NavSection =
  | "overview"
  | "commerce"
  | "marketplace"
  | "verticals"
  | "marketing"
  | "organization"
  | "cms"
  | "platform"
  | "system"

export interface ModuleDefinition {
  key: string
  icon: string
  section: NavSection
  scope: ModuleScope
  minWeight: number
  path: string
}

export const NAV_SECTION_LABELS: Record<NavSection, string> = {
  overview: "Overview",
  commerce: "Commerce",
  marketplace: "Marketplace",
  verticals: "Verticals",
  marketing: "Marketing",
  organization: "Organization",
  cms: "Content",
  platform: "Platform",
  system: "System",
}

export const NAV_SECTION_ORDER: NavSection[] = [
  "overview",
  "commerce",
  "marketplace",
  "verticals",
  "marketing",
  "cms",
  "organization",
  "platform",
  "system",
]

export const MODULE_REGISTRY: ModuleDefinition[] = [
  {
    key: "dashboard",
    icon: "SquaresPlus",
    section: "overview",
    scope: "tenant",
    minWeight: 40,
    path: "",
  },

  {
    key: "products",
    icon: "ShoppingBag",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/products",
  },
  {
    key: "orders",
    icon: "DocumentText",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/orders",
  },
  {
    key: "customers",
    icon: "Users",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/customers",
  },
  {
    key: "quotes",
    icon: "Tag",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/quotes",
  },
  {
    key: "invoices",
    icon: "Cash",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/invoices",
  },
  {
    key: "subscriptions",
    icon: "ArrowPath",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/subscriptions",
  },
  {
    key: "reviews",
    icon: "Star",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/reviews",
  },
  {
    key: "disputes",
    icon: "ChatBubble",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/disputes",
  },
  {
    key: "inventory",
    icon: "ShoppingBag",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/inventory",
  },
  {
    key: "shipping",
    icon: "TruckFast",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/shipping-extensions",
  },
  {
    key: "cart-extensions",
    icon: "ShoppingBag",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/cart-extensions",
  },
  {
    key: "purchase-orders",
    icon: "DocumentText",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/purchase-orders",
  },
  {
    key: "subscription-plans",
    icon: "ArrowPath",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/subscription-plans",
  },
  {
    key: "payment-terms",
    icon: "Cash",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/payment-terms",
  },
  {
    key: "service-providers",
    icon: "Users",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/service-providers",
  },
  {
    key: "inventory-extension",
    icon: "ShoppingBag",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/inventory-extension",
  },
  {
    key: "pricing-tiers",
    icon: "Cash",
    section: "commerce",
    scope: "tenant",
    minWeight: 40,
    path: "/pricing-tiers",
  },

  {
    key: "vendors",
    icon: "BuildingStorefront",
    section: "marketplace",
    scope: "shared",
    minWeight: 40,
    path: "/vendors",
  },
  {
    key: "commissions",
    icon: "ArrowUpDown",
    section: "marketplace",
    scope: "shared",
    minWeight: 40,
    path: "/commissions",
  },
  {
    key: "payouts",
    icon: "Cash",
    section: "marketplace",
    scope: "shared",
    minWeight: 40,
    path: "/payouts",
  },
  {
    key: "affiliates",
    icon: "Sparkles",
    section: "marketplace",
    scope: "tenant",
    minWeight: 40,
    path: "/affiliates",
  },

  {
    key: "auctions",
    icon: "Bolt",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/auctions",
  },
  {
    key: "bookings",
    icon: "Calendar",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/bookings",
  },
  {
    key: "event-ticketing",
    icon: "Calendar",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/event-ticketing",
  },
  {
    key: "rentals",
    icon: "TruckFast",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/rentals",
  },
  {
    key: "restaurants",
    icon: "ChefHat",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/restaurants",
  },
  {
    key: "grocery",
    icon: "ShoppingBag",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/grocery",
  },
  {
    key: "travel",
    icon: "Sparkles",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/travel",
  },
  {
    key: "automotive",
    icon: "TruckFast",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/automotive",
  },
  {
    key: "real-estate",
    icon: "Buildings",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/real-estate",
  },
  {
    key: "healthcare",
    icon: "Heart",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/healthcare",
  },
  {
    key: "education",
    icon: "AcademicCap",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/education",
  },
  {
    key: "fitness",
    icon: "Bolt",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/fitness",
  },
  {
    key: "pet-services",
    icon: "Heart",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/pet-services",
  },
  {
    key: "digital-products",
    icon: "RocketLaunch",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/digital-products",
  },
  {
    key: "memberships",
    icon: "Bookmarks",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/memberships",
  },
  {
    key: "financial-products",
    icon: "Cash",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/financial-products",
  },
  {
    key: "freelance",
    icon: "RocketLaunch",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/freelance",
  },
  {
    key: "parking",
    icon: "SquaresPlus",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/parking",
  },
  {
    key: "insurance",
    icon: "Heart",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/insurance",
  },
  {
    key: "government",
    icon: "Buildings",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/government",
  },
  {
    key: "trade-in",
    icon: "ArrowPath",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/trade-in",
  },
  {
    key: "try-before-you-buy",
    icon: "ShoppingBag",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/try-before-you-buy",
  },
  {
    key: "white-label",
    icon: "Tag",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/white-label",
  },
  {
    key: "volume-pricing",
    icon: "Cash",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/volume-pricing",
  },
  {
    key: "gift-cards",
    icon: "Sparkles",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/gift-cards",
  },
  {
    key: "warranties",
    icon: "Star",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/warranties",
  },
  {
    key: "flash-sales",
    icon: "Bolt",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/flash-sales",
  },
  {
    key: "consignments",
    icon: "TruckFast",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/consignments",
  },
  {
    key: "credit",
    icon: "Cash",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/credit",
  },
  {
    key: "dropshipping",
    icon: "TruckFast",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/dropshipping",
  },
  {
    key: "loyalty",
    icon: "Trophy",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/loyalty",
  },
  {
    key: "bundles",
    icon: "ShoppingBag",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/bundles",
  },
  {
    key: "wallet",
    icon: "Cash",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/wallet",
  },
  {
    key: "wishlists",
    icon: "Star",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/wishlists",
  },
  {
    key: "events",
    icon: "Calendar",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/events",
  },
  {
    key: "availability",
    icon: "Calendar",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/availability",
  },
  {
    key: "print-on-demand",
    icon: "RocketLaunch",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/print-on-demand",
  },
  {
    key: "flash-deals",
    icon: "Bolt",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/flash-deals",
  },
  {
    key: "b2b",
    icon: "Buildings",
    section: "verticals",
    scope: "tenant",
    minWeight: 40,
    path: "/b2b",
  },

  {
    key: "advertising",
    icon: "Target",
    section: "marketing",
    scope: "tenant",
    minWeight: 40,
    path: "/advertising",
  },
  {
    key: "promotions",
    icon: "Bolt",
    section: "marketing",
    scope: "tenant",
    minWeight: 40,
    path: "/promotions",
  },
  {
    key: "social-commerce",
    icon: "ChatBubble",
    section: "marketing",
    scope: "tenant",
    minWeight: 40,
    path: "/social-commerce",
  },
  {
    key: "classifieds",
    icon: "Tag",
    section: "marketing",
    scope: "tenant",
    minWeight: 40,
    path: "/classifieds",
  },
  {
    key: "crowdfunding",
    icon: "Trophy",
    section: "marketing",
    scope: "tenant",
    minWeight: 40,
    path: "/crowdfunding",
  },
  {
    key: "charity",
    icon: "Heart",
    section: "marketing",
    scope: "tenant",
    minWeight: 40,
    path: "/charities",
  },
  {
    key: "newsletters",
    icon: "DocumentText",
    section: "marketing",
    scope: "tenant",
    minWeight: 40,
    path: "/newsletters",
  },
  {
    key: "promotion-extensions",
    icon: "Bolt",
    section: "marketing",
    scope: "tenant",
    minWeight: 40,
    path: "/promotion-extensions",
  },

  {
    key: "cms-content",
    icon: "Bookmarks",
    section: "cms",
    scope: "tenant",
    minWeight: 30,
    path: "/cms-content",
  },
  {
    key: "media-library",
    icon: "Sparkles",
    section: "cms",
    scope: "tenant",
    minWeight: 30,
    path: "/media",
  },
  {
    key: "navigation",
    icon: "SquaresPlus",
    section: "cms",
    scope: "tenant",
    minWeight: 30,
    path: "/navigation",
  },
  {
    key: "payload",
    icon: "RocketLaunch",
    section: "cms",
    scope: "platform",
    minWeight: 90,
    path: "/payload-cms",
  },

  {
    key: "team",
    icon: "Users",
    section: "organization",
    scope: "tenant",
    minWeight: 40,
    path: "/team",
  },
  {
    key: "companies",
    icon: "Buildings",
    section: "organization",
    scope: "tenant",
    minWeight: 40,
    path: "/companies",
  },
  {
    key: "stores",
    icon: "BuildingStorefront",
    section: "organization",
    scope: "tenant",
    minWeight: 40,
    path: "/stores",
  },
  {
    key: "legal",
    icon: "Book",
    section: "organization",
    scope: "tenant",
    minWeight: 40,
    path: "/legal",
  },
  {
    key: "utilities",
    icon: "Beaker",
    section: "organization",
    scope: "tenant",
    minWeight: 40,
    path: "/utilities",
  },

  {
    key: "tenants-admin",
    icon: "Buildings",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/tenants-admin",
  },
  {
    key: "governance",
    icon: "Book",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/governance",
  },
  {
    key: "region-zones",
    icon: "Target",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/region-zones",
  },
  {
    key: "webhooks",
    icon: "Bolt",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/webhooks",
  },
  {
    key: "integrations",
    icon: "RocketLaunch",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/integrations",
  },
  {
    key: "temporal",
    icon: "ArrowPath",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/temporal",
  },
  {
    key: "audit",
    icon: "Book",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/audit",
  },
  {
    key: "nodes",
    icon: "SquaresPlus",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/nodes",
  },
  {
    key: "personas",
    icon: "Users",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/personas",
  },
  {
    key: "channels",
    icon: "RocketLaunch",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/channels",
  },
  {
    key: "i18n",
    icon: "Sparkles",
    section: "platform",
    scope: "platform",
    minWeight: 90,
    path: "/i18n",
  },

  {
    key: "analytics",
    icon: "ChartBar",
    section: "system",
    scope: "tenant",
    minWeight: 40,
    path: "/analytics",
  },
  {
    key: "settings",
    icon: "CogSixTooth",
    section: "system",
    scope: "tenant",
    minWeight: 40,
    path: "/settings",
  },
  {
    key: "metrics",
    icon: "ChartBar",
    section: "system",
    scope: "tenant",
    minWeight: 40,
    path: "/metrics",
  },
  {
    key: "notification-preferences",
    icon: "CogSixTooth",
    section: "system",
    scope: "tenant",
    minWeight: 40,
    path: "/notification-preferences",
  },
  {
    key: "tax-config",
    icon: "Cash",
    section: "system",
    scope: "tenant",
    minWeight: 40,
    path: "/tax-config",
  },
  // ── Horizontal Engine Modules ──────────────────────────────────────────
  {
    key: "order-orchestration",
    icon: "ArrowsPointingOut",
    section: "system",
    scope: "tenant",
    minWeight: 60,
    path: "/order-orchestration",
  },
  {
    key: "rma",
    icon: "ArrowUturnLeft",
    section: "commerce",
    scope: "tenant",
    minWeight: 60,
    path: "/rma",
  },
  {
    key: "settlement",
    icon: "BankNotes",
    section: "platform",
    scope: "tenant",
    minWeight: 60,
    path: "/settlement",
  },
  {
    key: "entitlements",
    icon: "Key",
    section: "system",
    scope: "tenant",
    minWeight: 60,
    path: "/entitlements",
  },
  {
    key: "fraud",
    icon: "ShieldExclamation",
    section: "system",
    scope: "tenant",
    minWeight: 60,
    path: "/fraud",
  },
  {
    key: "approval-workflow",
    icon: "CheckCircle",
    section: "system",
    scope: "tenant",
    minWeight: 60,
    path: "/approval-workflow",
  },
  {
    key: "attribution",
    icon: "ChartBar",
    section: "marketing",
    scope: "tenant",
    minWeight: 60,
    path: "/attribution",
  },
  // ── Wave 2 — Enterprise Engine Modules ────────────────────────────────
  {
    key: "chargeback",
    icon: "CreditCard",
    section: "platform",
    scope: "tenant",
    minWeight: 60,
    path: "/chargeback",
  },
  {
    key: "reconciliation",
    icon: "DocumentText",
    section: "platform",
    scope: "tenant",
    minWeight: 60,
    path: "/reconciliation",
  },
  {
    key: "search",
    icon: "MagnifyingGlass",
    section: "system",
    scope: "tenant",
    minWeight: 60,
    path: "/search",
  },
  {
    key: "tax-artifact",
    icon: "ReceiptPercent",
    section: "platform",
    scope: "tenant",
    minWeight: 60,
    path: "/tax-artifact",
  },
  {
    key: "pricing-resolver",
    icon: "Adjustments",
    section: "platform",
    scope: "tenant",
    minWeight: 60,
    path: "/pricing-resolver",
  },
]

export function getModulesBySection(
  maxWeight: number = 100,
): Record<NavSection, ModuleDefinition[]> {
  const grouped = {} as Record<NavSection, ModuleDefinition[]>
  for (const section of NAV_SECTION_ORDER) {
    grouped[section] = []
  }
  for (const mod of MODULE_REGISTRY) {
    if (mod.minWeight <= maxWeight) {
      grouped[mod.section].push(mod)
    }
  }
  return grouped
}
