import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import { handleApiError } from "../../../../lib/api-error-handler"

const SEED_RESTAURANTS = [
  { id: "rst-1", name: "Al Najd Village", description: "Authentic Najdi cuisine served in a traditional setting with live oud music. Famous for kabsa, jareesh, and haneeth.", cuisine_type: "najdi", cuisine: "Najdi", city: "Riyadh", phone: "+966 11 234 5678", rating: 4.8, review_count: 1240, price_range: "$$$", operating_hours: "12:00 PM – 12:00 AM", delivery_available: true, pickup_available: true, dine_in_available: true, metadata: { thumbnail: "/seed-images/restaurants%2F1555396273-367ea4eb4db5.jpg" }, features: ["Live oud music", "Private dining rooms", "Outdoor seating", "Halal certified"], menu: [{ category: "Main Dishes", items: [{ name: "Kabsa", description: "Traditional spiced rice with tender lamb", price: 65 }, { name: "Jareesh", description: "Crushed wheat cooked with meat and spices", price: 45 }, { name: "Haneeth", description: "Slow-roasted lamb on a bed of rice", price: 85 }] }, { category: "Appetizers", items: [{ name: "Samboosa", description: "Crispy pastry filled with spiced meat", price: 20 }, { name: "Mutabbaq", description: "Stuffed pan-fried bread", price: 25 }] }] },
  { id: "rst-2", name: "Sakura Japanese Kitchen", description: "Premium Japanese dining featuring fresh sushi, sashimi, and teppanyaki prepared by Tokyo-trained chefs.", cuisine_type: "japanese", cuisine: "Japanese", city: "Jeddah", phone: "+966 12 345 6789", rating: 4.7, review_count: 856, price_range: "$$$$", operating_hours: "1:00 PM – 11:30 PM", delivery_available: true, pickup_available: true, dine_in_available: true, metadata: { thumbnail: "/seed-images/restaurants%2F1579871494447-9811cf80d66c.jpg" }, features: ["Teppanyaki counter", "Sake bar", "Private tatami rooms", "Omakase menu"], menu: [{ category: "Sushi & Sashimi", items: [{ name: "Chef's Sushi Platter", description: "12-piece selection of premium nigiri", price: 120 }, { name: "Salmon Sashimi", description: "Fresh Norwegian salmon, thinly sliced", price: 65 }] }, { category: "Hot Dishes", items: [{ name: "Wagyu Teppanyaki", description: "A5 Wagyu grilled tableside", price: 180 }, { name: "Tempura Moriawase", description: "Assorted shrimp and vegetable tempura", price: 55 }] }] },
  { id: "rst-3", name: "Mama's Italian Kitchen", description: "Family-style Italian restaurant with handmade pasta, wood-fired pizzas, and an extensive selection of desserts.", cuisine_type: "italian", cuisine: "Italian", city: "Riyadh", phone: "+966 11 456 7890", rating: 4.6, review_count: 678, price_range: "$$", operating_hours: "11:00 AM – 11:00 PM", delivery_available: true, pickup_available: true, dine_in_available: true, metadata: { thumbnail: "/seed-images/restaurants%2F1517248135467-4c7edcad34c4.jpg" }, features: ["Wood-fired oven", "Family-style portions", "Kids menu", "Gluten-free options"], menu: [{ category: "Pasta", items: [{ name: "Truffle Tagliatelle", description: "Fresh handmade pasta with black truffle", price: 75 }, { name: "Spaghetti Carbonara", description: "Classic Roman-style with guanciale", price: 50 }] }, { category: "Pizza", items: [{ name: "Margherita", description: "San Marzano tomatoes, fresh mozzarella, basil", price: 40 }, { name: "Quattro Formaggi", description: "Four cheese blend with truffle honey", price: 55 }] }] },
  { id: "rst-4", name: "Spice Route Indian Bistro", description: "Vibrant Indian flavors from North and South India. Signature tandoori dishes, biryanis, and freshly baked naan bread.", cuisine_type: "indian", cuisine: "Indian", city: "Dammam", phone: "+966 13 567 8901", rating: 4.5, review_count: 432, price_range: "$$", operating_hours: "12:00 PM – 11:30 PM", delivery_available: true, pickup_available: true, dine_in_available: true, metadata: { thumbnail: "/seed-images/restaurants%2F1585937421612-70a008356fbe.jpg" }, features: ["Tandoor oven", "Vegetarian friendly", "Spice level customization", "Buffet on weekends"], menu: [{ category: "Tandoori", items: [{ name: "Tandoori Chicken", description: "Marinated overnight in yogurt and spices", price: 45 }, { name: "Seekh Kebab", description: "Minced lamb grilled on skewers", price: 40 }] }, { category: "Biryani", items: [{ name: "Hyderabadi Biryani", description: "Fragrant basmati rice with tender goat meat", price: 55 }, { name: "Vegetable Biryani", description: "Seasonal vegetables with aromatic rice", price: 35 }] }] },
  { id: "rst-5", name: "The Arabian Table", description: "Modern Arabic cuisine with a contemporary twist. Featuring mezzeh platters, grilled meats, and traditional sweets.", cuisine_type: "arabic", cuisine: "Arabic", city: "Riyadh", phone: "+966 11 678 9012", rating: 4.9, review_count: 1567, price_range: "$$$", operating_hours: "10:00 AM – 1:00 AM", delivery_available: true, pickup_available: false, dine_in_available: true, metadata: { thumbnail: "/seed-images/bundles%2F1504674900247-0877df9cc836.jpg" }, features: ["Rooftop terrace", "Shisha lounge", "Live Arabic music", "Catering available"], menu: [{ category: "Mezzeh", items: [{ name: "Hummus", description: "Creamy chickpea dip with olive oil", price: 18 }, { name: "Fattoush", description: "Fresh salad with crispy pita chips", price: 22 }] }, { category: "Grills", items: [{ name: "Mixed Grill Platter", description: "Lamb chops, chicken, and kofta", price: 95 }, { name: "Whole Roasted Lamb", description: "Served with rice and nuts (serves 6)", price: 450 }] }] },
  { id: "rst-6", name: "Bangkok Street Kitchen", description: "Authentic Thai street food brought to life with bold flavors. Known for pad thai, green curry, and mango sticky rice.", cuisine_type: "thai", cuisine: "Thai", city: "Jeddah", phone: "+966 12 789 0123", rating: 4.4, review_count: 298, price_range: "$", operating_hours: "11:30 AM – 10:30 PM", delivery_available: true, pickup_available: true, dine_in_available: false, metadata: { thumbnail: "/seed-images/restaurants%2F1562565652-a0d8f0c59eb4.jpg" }, features: ["Street food style", "Wok-fired dishes", "Vegan options", "Quick service"], menu: [{ category: "Noodles", items: [{ name: "Pad Thai", description: "Stir-fried rice noodles with shrimp and peanuts", price: 35 }, { name: "Pad See Ew", description: "Wide noodles with dark soy and Chinese broccoli", price: 30 }] }, { category: "Curries", items: [{ name: "Green Curry", description: "Coconut milk curry with chicken and Thai basil", price: 38 }, { name: "Massaman Curry", description: "Rich curry with potatoes and peanuts", price: 40 }] }] },
]

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  try {
    const mod = req.scope.resolve("restaurant") as any
    const { id } = req.params
    const restaurant = await mod.retrieveRestaurant(id)
    if (!restaurant) {
      const seed = SEED_RESTAURANTS.find((s) => s.id === id) || SEED_RESTAURANTS[0]
      return res.json({ item: { ...seed, id, menus: [] } })
    }
    const menus = await mod.listMenus({ restaurant_id: id }, { take: 10 })
    return res.json({ item: { ...restaurant, menus } })
  } catch (error: any) {
    const { id } = req.params
    const seed = SEED_RESTAURANTS.find((s) => s.id === id) || SEED_RESTAURANTS[0]
    return res.json({ item: { ...seed, id, menus: [] } })
  }
}

