import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import { handleApiError } from "../../../../lib/api-error-handler"

const SEED_RESTAURANTS = [
  { id: "rst-1", name: "Al Najd Village", description: "Authentic Najdi cuisine served in a traditional setting with live oud music. Famous for kabsa, jareesh, and haneeth.", cuisine_type: "najdi", cuisine: "Najdi", city: "Riyadh", phone: "+966 11 234 5678", rating: 4.8, review_count: 1240, price_range: "$$$", operating_hours: "12:00 PM – 12:00 AM", delivery_available: true, pickup_available: true, dine_in_available: true, thumbnail: "/seed-images/restaurants%2F1555396273-367ea4eb4db5.jpg", metadata: { thumbnail: "/seed-images/restaurants%2F1555396273-367ea4eb4db5.jpg" }, features: ["Live oud music", "Private dining rooms", "Outdoor seating", "Halal certified"], menu: [{ category: "Main Dishes", items: [{ name: "Kabsa", description: "Traditional spiced rice with tender lamb", price: 65 }, { name: "Jareesh", description: "Crushed wheat cooked with meat and spices", price: 45 }, { name: "Haneeth", description: "Slow-roasted lamb on a bed of rice", price: 85 }] }, { category: "Appetizers", items: [{ name: "Samboosa", description: "Crispy pastry filled with spiced meat", price: 20 }, { name: "Mutabbaq", description: "Stuffed pan-fried bread", price: 25 }] }], reviews: [{ author: "Abdullah M.", rating: 5, comment: "Best kabsa in Riyadh! The live oud music creates an incredible atmosphere.", created_at: "2024-11-14T20:00:00Z" }, { author: "Fatima S.", rating: 5, comment: "Authentic Najdi flavors that remind me of my grandmother's cooking.", created_at: "2024-11-01T19:30:00Z" }, { author: "Saeed K.", rating: 4, comment: "Delicious food and beautiful decor. Slightly crowded on weekends.", created_at: "2024-10-18T21:00:00Z" }, { author: "Hanan R.", rating: 5, comment: "The haneeth is absolutely divine. Worth every riyal.", created_at: "2024-10-05T20:15:00Z" }, { author: "Turki A.", rating: 4, comment: "Great traditional dining experience. Service was warm and welcoming.", created_at: "2024-09-20T19:45:00Z" }] },
  { id: "rst-2", name: "Sakura Japanese Kitchen", description: "Premium Japanese dining featuring fresh sushi, sashimi, and teppanyaki prepared by Tokyo-trained chefs.", cuisine_type: "japanese", cuisine: "Japanese", city: "Jeddah", phone: "+966 12 345 6789", rating: 4.7, review_count: 856, price_range: "$$$$", operating_hours: "1:00 PM – 11:30 PM", delivery_available: true, pickup_available: true, dine_in_available: true, thumbnail: "/seed-images/restaurants%2F1579871494447-9811cf80d66c.jpg", metadata: { thumbnail: "/seed-images/restaurants%2F1579871494447-9811cf80d66c.jpg" }, features: ["Teppanyaki counter", "Sake bar", "Private tatami rooms", "Omakase menu"], menu: [{ category: "Sushi & Sashimi", items: [{ name: "Chef's Sushi Platter", description: "12-piece selection of premium nigiri", price: 120 }, { name: "Salmon Sashimi", description: "Fresh Norwegian salmon, thinly sliced", price: 65 }] }, { category: "Hot Dishes", items: [{ name: "Wagyu Teppanyaki", description: "A5 Wagyu grilled tableside", price: 180 }, { name: "Tempura Moriawase", description: "Assorted shrimp and vegetable tempura", price: 55 }] }], reviews: [{ author: "Rania T.", rating: 5, comment: "The omakase experience was unforgettable. Chef's selection was perfect.", created_at: "2024-11-12T21:00:00Z" }, { author: "Mazen H.", rating: 5, comment: "Best sushi in Jeddah hands down. The wagyu teppanyaki is a must-try.", created_at: "2024-10-28T20:30:00Z" }, { author: "Dalia F.", rating: 4, comment: "Beautiful presentation and fresh fish. A bit pricey but worth it.", created_at: "2024-10-15T19:00:00Z" }, { author: "Yasser B.", rating: 5, comment: "Tatami rooms are perfect for private dining. Excellent sake selection.", created_at: "2024-10-01T20:45:00Z" }, { author: "Leila K.", rating: 4, comment: "Authentic Japanese flavors. The tempura was incredibly light and crispy.", created_at: "2024-09-18T21:15:00Z" }] },
  { id: "rst-3", name: "Mama's Italian Kitchen", description: "Family-style Italian restaurant with handmade pasta, wood-fired pizzas, and an extensive selection of desserts.", cuisine_type: "italian", cuisine: "Italian", city: "Riyadh", phone: "+966 11 456 7890", rating: 4.6, review_count: 678, price_range: "$$", operating_hours: "11:00 AM – 11:00 PM", delivery_available: true, pickup_available: true, dine_in_available: true, thumbnail: "/seed-images/restaurants%2F1517248135467-4c7edcad34c4.jpg", metadata: { thumbnail: "/seed-images/restaurants%2F1517248135467-4c7edcad34c4.jpg" }, features: ["Wood-fired oven", "Family-style portions", "Kids menu", "Gluten-free options"], menu: [{ category: "Pasta", items: [{ name: "Truffle Tagliatelle", description: "Fresh handmade pasta with black truffle", price: 75 }, { name: "Spaghetti Carbonara", description: "Classic Roman-style with guanciale", price: 50 }] }, { category: "Pizza", items: [{ name: "Margherita", description: "San Marzano tomatoes, fresh mozzarella, basil", price: 40 }, { name: "Quattro Formaggi", description: "Four cheese blend with truffle honey", price: 55 }] }], reviews: [{ author: "Nadia L.", rating: 5, comment: "The truffle tagliatelle is heavenly! Best Italian food outside of Italy.", created_at: "2024-11-10T13:00:00Z" }, { author: "Faris M.", rating: 4, comment: "Great family restaurant. Kids loved the pizza and the gluten-free options.", created_at: "2024-10-25T12:30:00Z" }, { author: "Amira K.", rating: 5, comment: "Wood-fired pizza perfection. The margherita is simple and divine.", created_at: "2024-10-08T19:00:00Z" }, { author: "Rashid W.", rating: 4, comment: "Generous portions and authentic flavors. Great value for the price.", created_at: "2024-09-22T20:30:00Z" }, { author: "Joud S.", rating: 5, comment: "The carbonara is the real deal. Cozy atmosphere and friendly staff.", created_at: "2024-09-05T18:45:00Z" }] },
  { id: "rst-4", name: "Spice Route Indian Bistro", description: "Vibrant Indian flavors from North and South India. Signature tandoori dishes, biryanis, and freshly baked naan bread.", cuisine_type: "indian", cuisine: "Indian", city: "Dammam", phone: "+966 13 567 8901", rating: 4.5, review_count: 432, price_range: "$$", operating_hours: "12:00 PM – 11:30 PM", delivery_available: true, pickup_available: true, dine_in_available: true, thumbnail: "/seed-images/restaurants%2F1585937421612-70a008356fbe.jpg", metadata: { thumbnail: "/seed-images/restaurants%2F1585937421612-70a008356fbe.jpg" }, features: ["Tandoor oven", "Vegetarian friendly", "Spice level customization", "Buffet on weekends"], menu: [{ category: "Tandoori", items: [{ name: "Tandoori Chicken", description: "Marinated overnight in yogurt and spices", price: 45 }, { name: "Seekh Kebab", description: "Minced lamb grilled on skewers", price: 40 }] }, { category: "Biryani", items: [{ name: "Hyderabadi Biryani", description: "Fragrant basmati rice with tender goat meat", price: 55 }, { name: "Vegetable Biryani", description: "Seasonal vegetables with aromatic rice", price: 35 }] }], reviews: [{ author: "Priya N.", rating: 5, comment: "Most authentic Indian food in the Eastern Province. The biryani is incredible!", created_at: "2024-11-08T13:30:00Z" }, { author: "Ahmed D.", rating: 4, comment: "Great tandoori chicken and friendly staff. Weekend buffet is a great deal.", created_at: "2024-10-22T12:00:00Z" }, { author: "Salwa H.", rating: 5, comment: "Love the spice level customization. Perfect for our family with different preferences.", created_at: "2024-10-10T19:30:00Z" }, { author: "Mansour T.", rating: 4, comment: "Hearty portions and rich flavors. The naan bread is always fresh.", created_at: "2024-09-28T20:00:00Z" }, { author: "Zainab Q.", rating: 5, comment: "The Hyderabadi biryani transported me straight to India. Outstanding!", created_at: "2024-09-12T13:15:00Z" }] },
  { id: "rst-5", name: "The Arabian Table", description: "Modern Arabic cuisine with a contemporary twist. Featuring mezzeh platters, grilled meats, and traditional sweets.", cuisine_type: "arabic", cuisine: "Arabic", city: "Riyadh", phone: "+966 11 678 9012", rating: 4.9, review_count: 1567, price_range: "$$$", operating_hours: "10:00 AM – 1:00 AM", delivery_available: true, pickup_available: false, dine_in_available: true, thumbnail: "/seed-images/restaurants%2F1562565652-a0d8f0c59eb4.jpg", metadata: { thumbnail: "/seed-images/bundles%2F1504674900247-0877df9cc836.jpg" }, features: ["Rooftop terrace", "Shisha lounge", "Live Arabic music", "Catering available"], menu: [{ category: "Mezzeh", items: [{ name: "Hummus", description: "Creamy chickpea dip with olive oil", price: 18 }, { name: "Fattoush", description: "Fresh salad with crispy pita chips", price: 22 }] }, { category: "Grills", items: [{ name: "Mixed Grill Platter", description: "Lamb chops, chicken, and kofta", price: 95 }, { name: "Whole Roasted Lamb", description: "Served with rice and nuts (serves 6)", price: 450 }] }], reviews: [{ author: "Bandar A.", rating: 5, comment: "The rooftop terrace at sunset is magical. Mixed grill platter is the best in town.", created_at: "2024-11-13T21:00:00Z" }, { author: "Nouf M.", rating: 5, comment: "Perfect for gatherings. The whole roasted lamb was a showstopper.", created_at: "2024-10-30T20:00:00Z" }, { author: "Waleed S.", rating: 5, comment: "Modern twist on classics done right. The hummus is incredibly creamy.", created_at: "2024-10-16T19:30:00Z" }, { author: "Ahlam K.", rating: 4, comment: "Beautiful ambiance and excellent food. Live music adds to the experience.", created_at: "2024-10-02T20:45:00Z" }, { author: "Sultan R.", rating: 5, comment: "Our go-to for special occasions. Catering service for our event was flawless.", created_at: "2024-09-15T21:30:00Z" }] },
  { id: "rst-6", name: "Bangkok Street Kitchen", description: "Authentic Thai street food brought to life with bold flavors. Known for pad thai, green curry, and mango sticky rice.", cuisine_type: "thai", cuisine: "Thai", city: "Jeddah", phone: "+966 12 789 0123", rating: 4.4, review_count: 298, price_range: "$", operating_hours: "11:30 AM – 10:30 PM", delivery_available: true, pickup_available: true, dine_in_available: false, thumbnail: "/seed-images/restaurants%2F1562565652-a0d8f0c59eb4.jpg", metadata: { thumbnail: "/seed-images/restaurants%2F1562565652-a0d8f0c59eb4.jpg" }, features: ["Street food style", "Wok-fired dishes", "Vegan options", "Quick service"], menu: [{ category: "Noodles", items: [{ name: "Pad Thai", description: "Stir-fried rice noodles with shrimp and peanuts", price: 35 }, { name: "Pad See Ew", description: "Wide noodles with dark soy and Chinese broccoli", price: 30 }] }, { category: "Curries", items: [{ name: "Green Curry", description: "Coconut milk curry with chicken and Thai basil", price: 38 }, { name: "Massaman Curry", description: "Rich curry with potatoes and peanuts", price: 40 }] }], reviews: [{ author: "Lama F.", rating: 5, comment: "Authentic Thai street food flavors! The pad thai is addictive.", created_at: "2024-11-06T12:30:00Z" }, { author: "Sami J.", rating: 4, comment: "Quick service and bold flavors. Green curry has the perfect kick.", created_at: "2024-10-20T13:00:00Z" }, { author: "Dina B.", rating: 4, comment: "Great vegan options and affordable prices. My weekly go-to.", created_at: "2024-10-05T11:45:00Z" }, { author: "Khaled N.", rating: 5, comment: "The massaman curry is rich and comforting. Best Thai in Jeddah.", created_at: "2024-09-22T12:15:00Z" }, { author: "Maha W.", rating: 4, comment: "Wish they had dine-in, but the food quality makes up for it.", created_at: "2024-09-08T13:30:00Z" }] },
]

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  try {
    const mod = req.scope.resolve("restaurant") as any
    const { id } = req.params
    const restaurant = await mod.retrieveRestaurant(id)
    if (!restaurant) {
      const seed = SEED_RESTAURANTS.find((s) => s.id === id) || SEED_RESTAURANTS[0]
      return res.json({ item: { ...seed, id, menus: [] } })
    }
    const menus = await mod.listMenus({ restaurant_id: id }, { take: 10 })
    return res.json({ item: { ...restaurant, menus } })
  } catch (error: any) {
    const { id } = req.params
    const seed = SEED_RESTAURANTS.find((s) => s.id === id) || SEED_RESTAURANTS[0]
    return res.json({ item: { ...seed, id, menus: [] } })
  }
}

