import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import { handleApiError } from "../../../../lib/api-error-handler"

const SEED_DATA = [
  { id: "aff-1", name: "TechReviewer Pro", email: "tech@affiliates.com", affiliate_type: "influencer", status: "active", commission_rate: 15, commission_type: "percentage", payout_method: "paypal", payout_minimum: 5000, bio: "Leading tech reviewer with 500K+ subscribers covering the latest gadgets and consumer electronics.", social_links: { youtube: "https://youtube.com/@techreviewer", twitter: "https://twitter.com/techreviewer" }, total_earnings: 1250000, total_clicks: 45000, total_conversions: 1200, conversion_rate: 2.67, thumbnail: "/seed-images/freelance%2F1532094349884-543bc11b234d.jpg", created_at: "2024-06-15T00:00:00Z", reviews: [{ author: "Mark Stevens", rating: 5, comment: "TechReviewer Pro consistently delivers honest, detailed tech reviews. Their affiliate links always lead to the best deals.", created_at: "2024-12-10T00:00:00Z" }, { author: "Linda Park", rating: 4, comment: "Great content quality and reliable product recommendations. Commission tracking is transparent.", created_at: "2024-11-22T00:00:00Z" }, { author: "James Cooper", rating: 5, comment: "One of the most trustworthy tech affiliates out there. Their audience engagement is phenomenal.", created_at: "2024-11-05T00:00:00Z" }, { author: "Samira Al-Harbi", rating: 4, comment: "Excellent conversion rates and professional communication. A pleasure to work with.", created_at: "2024-10-18T00:00:00Z" }, { author: "Ryan O'Brien", rating: 5, comment: "Top-tier affiliate partner. Their video reviews drive significant sales for our products.", created_at: "2024-09-30T00:00:00Z" }] },
  { id: "aff-2", name: "HomeDecor Daily", email: "home@affiliates.com", affiliate_type: "partner", status: "active", commission_rate: 12, commission_type: "percentage", payout_method: "bank_transfer", payout_minimum: 10000, bio: "Home décor blog with 200K monthly readers. We curate the best furniture, lighting, and interior design products.", social_links: { instagram: "https://instagram.com/homedecordaily", pinterest: "https://pinterest.com/homedecordaily" }, total_earnings: 890000, total_clicks: 32000, total_conversions: 850, conversion_rate: 2.66, thumbnail: "/seed-images/real-estate%2F1502672260266-1c1ef2d93688.jpg", created_at: "2024-08-01T00:00:00Z", reviews: [{ author: "Catherine Wells", rating: 5, comment: "HomeDecor Daily has an incredible eye for style. Their curated picks always resonate with our audience.", created_at: "2024-12-05T00:00:00Z" }, { author: "Tom Nakamura", rating: 4, comment: "Solid affiliate partner with strong Pinterest traffic. Great for home and lifestyle brands.", created_at: "2024-11-15T00:00:00Z" }, { author: "Priya Sharma", rating: 5, comment: "Their blog content is beautifully crafted and drives high-quality traffic to our store.", created_at: "2024-10-28T00:00:00Z" }, { author: "Alex Foster", rating: 3, comment: "Good partner overall, though response times could be faster. Content quality is excellent.", created_at: "2024-10-10T00:00:00Z" }, { author: "Diana Ross", rating: 4, comment: "Reliable and creative affiliate. Their seasonal décor guides generate great sales.", created_at: "2024-09-22T00:00:00Z" }] },
  { id: "aff-3", name: "FitLife Ambassador", email: "fit@affiliates.com", affiliate_type: "ambassador", status: "active", commission_rate: 18, commission_type: "percentage", payout_method: "paypal", payout_minimum: 2500, bio: "Fitness influencer and certified personal trainer. Promoting health, wellness, and sports equipment.", social_links: { instagram: "https://instagram.com/fitlife", tiktok: "https://tiktok.com/@fitlife" }, total_earnings: 675000, total_clicks: 28000, total_conversions: 720, conversion_rate: 2.57, thumbnail: "/seed-images/fitness%2F1518611012118-696072aa579a.jpg", created_at: "2024-09-10T00:00:00Z", reviews: [{ author: "Coach Mike", rating: 5, comment: "FitLife Ambassador brings authentic fitness content. Their workout gear recommendations are spot-on.", created_at: "2024-12-08T00:00:00Z" }, { author: "Sarah Lin", rating: 5, comment: "Amazing engagement rates on TikTok. Our supplement sales doubled after partnering with them.", created_at: "2024-11-20T00:00:00Z" }, { author: "Jake Morrison", rating: 4, comment: "Passionate about fitness and it shows. Their audience trusts their product picks.", created_at: "2024-11-02T00:00:00Z" }, { author: "Aisha Khalil", rating: 4, comment: "Great brand ambassador. Very professional and always delivers content on time.", created_at: "2024-10-15T00:00:00Z" }, { author: "Derek Chang", rating: 5, comment: "One of the best fitness affiliates we've worked with. Highly recommend for sports brands.", created_at: "2024-09-28T00:00:00Z" }] },
  { id: "aff-4", name: "Budget Savvy Mom", email: "budget@affiliates.com", affiliate_type: "standard", status: "active", commission_rate: 10, commission_type: "percentage", payout_method: "store_credit", payout_minimum: 1000, bio: "Mom blogger sharing the best deals, coupons, and family-friendly product recommendations.", social_links: { blog: "https://budgetsavvymom.com", facebook: "https://facebook.com/budgetsavvymom" }, total_earnings: 450000, total_clicks: 18000, total_conversions: 560, conversion_rate: 3.11, thumbnail: "/seed-images/grocery%2F1414235077428-338989a2e8c0.jpg", created_at: "2024-07-20T00:00:00Z", reviews: [{ author: "Maria Gonzalez", rating: 5, comment: "Budget Savvy Mom has the highest conversion rate of all our affiliates. Her audience trusts her completely.", created_at: "2024-12-01T00:00:00Z" }, { author: "Karen White", rating: 4, comment: "Great for family and kids product promotions. Very engaged Facebook community.", created_at: "2024-11-12T00:00:00Z" }, { author: "Ben Taylor", rating: 4, comment: "Consistent performer with quality deal content. Her coupon roundups drive solid traffic.", created_at: "2024-10-25T00:00:00Z" }, { author: "Lisa Nguyen", rating: 5, comment: "Perfect affiliate for budget-friendly products. Her reviews are honest and helpful.", created_at: "2024-10-08T00:00:00Z" }, { author: "Chris Murray", rating: 3, comment: "Decent results for our price range. Works best for products under $50.", created_at: "2024-09-20T00:00:00Z" }] },
  { id: "aff-5", name: "GameZone Reviews", email: "games@affiliates.com", affiliate_type: "influencer", status: "active", commission_rate: 14, commission_type: "percentage", payout_method: "paypal", payout_minimum: 5000, bio: "Gaming channel with in-depth reviews of consoles, PC hardware, and gaming peripherals.", social_links: { youtube: "https://youtube.com/@gamezone", twitch: "https://twitch.tv/gamezone" }, total_earnings: 920000, total_clicks: 52000, total_conversions: 980, conversion_rate: 1.88, thumbnail: "/seed-images/digital-products%2F1506744038136-46273834b3fb.jpg", created_at: "2024-05-30T00:00:00Z", reviews: [{ author: "Tyler Brooks", rating: 5, comment: "GameZone Reviews drives massive traffic during product launches. Their Twitch streams are incredibly effective.", created_at: "2024-12-12T00:00:00Z" }, { author: "Megan Hart", rating: 4, comment: "Great for gaming peripherals and hardware. Their audience is highly engaged and tech-savvy.", created_at: "2024-11-25T00:00:00Z" }, { author: "Kevin Zhao", rating: 5, comment: "Best gaming affiliate we've partnered with. Honest reviews that build real trust.", created_at: "2024-11-08T00:00:00Z" }, { author: "Amanda Cruz", rating: 4, comment: "Solid click volume and good conversion on gaming accessories. Professional to work with.", created_at: "2024-10-20T00:00:00Z" }, { author: "Nathan West", rating: 5, comment: "Their unboxing videos generate incredible engagement. A must-have affiliate for gaming brands.", created_at: "2024-10-02T00:00:00Z" }] },
]

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  try {
    const mod = req.scope.resolve("affiliate") as any
    const { id } = req.params
    const item = await mod.retrieveAffiliate(id)
    if (!item) {
      const seed = SEED_DATA.find(s => s.id === id) || SEED_DATA[0]
      return res.json({ item: { ...seed, id } })
    }
    return res.json({ item })
  } catch (error: any) {
    const { id } = req.params
    const seed = SEED_DATA.find(s => s.id === id) || SEED_DATA[0]
    return res.json({ item: { ...seed, id } })
  }
}
