import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"

const SEED_SERVICES = [
  { id: "sp_01", service_name: "Deep Tissue Massage", description: "Professional deep tissue massage therapy to relieve chronic muscle tension and improve circulation.", provider: "Wellness Spa & Therapy Center", category: "wellness", duration: 60, price: 25000, currency: "SAR", rating: 4.9, review_count: 124, thumbnail: "/seed-images/bookings%2F1544161515-4ab6ce6db874.jpg", location: "Riyadh", availability: "Daily 9AM-9PM", reviews: [{ author: "Nora Al-Harbi", rating: 5, comment: "Incredible deep tissue work. Left feeling completely renewed and pain-free.", created_at: "2025-01-15T00:00:00Z" }, { author: "James Wilson", rating: 5, comment: "The therapist targeted my problem areas perfectly. Highly skilled and professional.", created_at: "2025-01-10T00:00:00Z" }, { author: "Fatima Zahra", rating: 4, comment: "Excellent spa atmosphere and skilled therapists. Will definitely book again.", created_at: "2025-01-05T00:00:00Z" }, { author: "Mike Thompson", rating: 5, comment: "Best massage experience in Riyadh. The center is spotlessly clean.", created_at: "2024-12-28T00:00:00Z" }, { author: "Aisha Malik", rating: 4, comment: "Great value for a 60-minute session. Easy online booking process.", created_at: "2024-12-20T00:00:00Z" }] },
  { id: "sp_02", service_name: "Hair Styling & Color", description: "Expert hair styling, coloring, and treatment services for all hair types.", provider: "Glamour Hair Studio", category: "beauty", duration: 90, price: 35000, currency: "SAR", rating: 4.7, review_count: 89, thumbnail: "/seed-images/bookings%2F1560066984-138dadb4c035.jpg", location: "Jeddah", availability: "Mon-Sat 10AM-8PM", reviews: [{ author: "Lina Stylist", rating: 5, comment: "Glamour Hair Studio is the best in Jeddah. My color came out exactly as I wanted.", created_at: "2025-01-12T00:00:00Z" }, { author: "Maya Beauty", rating: 4, comment: "Expert colorist who understood my hair type. The 90-minute session was well-paced.", created_at: "2025-01-08T00:00:00Z" }, { author: "Sara Al-Fahad", rating: 5, comment: "Stunning results every visit. Their products are premium quality.", created_at: "2025-01-02T00:00:00Z" }, { author: "Jennifer Color", rating: 4, comment: "Great balayage work. The stylist was attentive and creative.", created_at: "2024-12-25T00:00:00Z" }, { author: "Amira Hair", rating: 3, comment: "Good service but weekends are very busy. Book early for the best stylists.", created_at: "2024-12-18T00:00:00Z" }] },
  { id: "sp_03", service_name: "Personal Training Session", description: "One-on-one personal training session with certified fitness coach.", provider: "FitLife Performance Center", category: "fitness", duration: 60, price: 20000, currency: "SAR", rating: 4.8, review_count: 156, thumbnail: "/seed-images/bookings%2F1534438327276-14e5300c3a48.jpg", location: "Riyadh", availability: "Daily 6AM-10PM", reviews: [{ author: "Khalid Fitness", rating: 5, comment: "My trainer at FitLife created a personalized program that delivered real results.", created_at: "2025-01-14T00:00:00Z" }, { author: "Dana Wellness", rating: 5, comment: "Certified coaches who know their craft. Lost 5kg in my first month of training.", created_at: "2025-01-09T00:00:00Z" }, { author: "Tom Athlete", rating: 4, comment: "Well-equipped facility and knowledgeable trainers. Great for all fitness levels.", created_at: "2025-01-03T00:00:00Z" }, { author: "Nadia Active", rating: 5, comment: "The one-on-one attention makes all the difference. My trainer pushes me just right.", created_at: "2024-12-27T00:00:00Z" }, { author: "Ali Gym", rating: 4, comment: "Flexible scheduling from 6AM to 10PM. Perfect for my busy work schedule.", created_at: "2024-12-19T00:00:00Z" }] },
  { id: "sp_04", service_name: "Home Cleaning Service", description: "Professional deep cleaning service for apartments and villas.", provider: "CleanPro Services", category: "home", duration: 180, price: 45000, currency: "SAR", rating: 4.6, review_count: 210, thumbnail: "/seed-images/bookings%2F1581578731548-c64695cc6952.jpg", location: "Multiple Cities", availability: "Daily 8AM-6PM", reviews: [{ author: "Reem Homeowner", rating: 5, comment: "CleanPro did an amazing job on our villa. Every corner was spotless after their visit.", created_at: "2025-01-13T00:00:00Z" }, { author: "Abdullah Family", rating: 4, comment: "Reliable and thorough cleaning. They brought all their own supplies and equipment.", created_at: "2025-01-07T00:00:00Z" }, { author: "Lisa Apartment", rating: 5, comment: "3-hour deep clean transformed my apartment. The team was professional and efficient.", created_at: "2025-01-01T00:00:00Z" }, { author: "Hassan Villa", rating: 4, comment: "Available in multiple cities which is convenient. Consistent quality every booking.", created_at: "2024-12-24T00:00:00Z" }, { author: "Sophie Clean", rating: 4, comment: "Good value for the comprehensive service. They pay attention to details.", created_at: "2024-12-16T00:00:00Z" }] },
  { id: "sp_05", service_name: "Car Detailing Premium", description: "Full interior and exterior car detailing with ceramic coating option.", provider: "AutoShine Detailing", category: "automotive", duration: 240, price: 55000, currency: "SAR", rating: 4.9, review_count: 78, thumbnail: "/seed-images/bookings%2F1520340356584-f9917d1eea6f.jpg", location: "Riyadh", availability: "Daily 7AM-7PM", reviews: [{ author: "Fahad Cars", rating: 5, comment: "AutoShine made my car look better than showroom condition. The ceramic coating is incredible.", created_at: "2025-01-11T00:00:00Z" }, { author: "Omar Detail", rating: 5, comment: "4 hours of meticulous work. Every surface gleams. Best detailing service in Riyadh.", created_at: "2025-01-06T00:00:00Z" }, { author: "Saud Auto", rating: 5, comment: "The interior detail was exceptional. Leather restored, carpets shampooed, everything perfect.", created_at: "2024-12-30T00:00:00Z" }, { author: "Mansoor Drive", rating: 4, comment: "Premium service at a fair price. The ceramic coating has lasted months.", created_at: "2024-12-22T00:00:00Z" }, { author: "Bader Wheels", rating: 5, comment: "They treat every car like it's their own. Highly recommend the full package.", created_at: "2024-12-14T00:00:00Z" }] },
  { id: "sp_06", service_name: "Photography Session", description: "Professional portrait, family, or event photography session.", provider: "Capture Moments Studio", category: "creative", duration: 120, price: 80000, currency: "SAR", rating: 4.8, review_count: 45, thumbnail: "/seed-images/bookings%2F1554048612-b6a482bc67e5.jpg", location: "Jeddah", availability: "By Appointment", reviews: [{ author: "Nadia Events", rating: 5, comment: "Capture Moments delivered stunning photos of our corporate event. Every key moment was covered.", created_at: "2025-01-10T00:00:00Z" }, { author: "Youssef Family", rating: 5, comment: "Our family portrait session was fun and the results were gorgeous. The photographer was patient with kids.", created_at: "2025-01-04T00:00:00Z" }, { author: "Emma Portraits", rating: 4, comment: "Professional studio and natural light options. The 2-hour session allowed for multiple setups.", created_at: "2024-12-28T00:00:00Z" }, { author: "Hassan Wedding", rating: 5, comment: "Beautiful event photography. The edited photos were delivered within a week.", created_at: "2024-12-20T00:00:00Z" }, { author: "Alex Product", rating: 4, comment: "Great product photography for our online store. Clean, professional shots.", created_at: "2024-12-12T00:00:00Z" }] },
]

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  try {
    const { id } = req.params
    const mod = req.scope.resolve("booking") as any
    const item = await mod.retrieveServiceProvider(id)
    if (item) return res.json({ item })
    const seed = SEED_SERVICES.find((s) => s.id === id) || SEED_SERVICES[0]
    return res.json({ item: { ...seed, id } })
  } catch {
    const { id } = req.params
    const seed = SEED_SERVICES.find((s) => s.id === id) || SEED_SERVICES[0]
    return res.json({ item: { ...seed, id } })
  }
}
