import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import { handleApiError } from "../../../../lib/api-error-handler"

const SEED_DATA = [
  {
    id: "auto_seed_1",
    tenant_id: "default",
    seller_id: "seller_1",
    listing_type: "sale",
    title: "2024 Toyota Land Cruiser",
    make: "Toyota",
    model_name: "Land Cruiser",
    year: 2024,
    mileage_km: 5200,
    fuel_type: "petrol",
    transmission: "automatic",
    body_type: "suv",
    color: "Pearl White",
    condition: "new",
    price: 28500000,
    currency_code: "SAR",
    description: "Brand new Toyota Land Cruiser with premium package, leather interior, and advanced safety features.",
    features: ["Adaptive Cruise Control", "360 Camera", "Premium Audio", "Heated Seats"],
    location_city: "Riyadh",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "/seed-images/automotive%2F1568605117036-5fe5e7bab0b7.jpg", price: 28500000, currency: "SAR", location: "Riyadh, Saudi Arabia" },
    thumbnail: "/seed-images/automotive%2F1568605117036-5fe5e7bab0b7.jpg",
  },
  {
    id: "auto_seed_2",
    tenant_id: "default",
    seller_id: "seller_2",
    listing_type: "sale",
    title: "2023 BMW X5 xDrive40i",
    make: "BMW",
    model_name: "X5",
    year: 2023,
    mileage_km: 18500,
    fuel_type: "petrol",
    transmission: "automatic",
    body_type: "suv",
    color: "Mineral White",
    condition: "certified_pre_owned",
    price: 22000000,
    currency_code: "SAR",
    description: "Certified pre-owned BMW X5 with M Sport package, panoramic sunroof, and Harman Kardon sound system.",
    features: ["M Sport Package", "Panoramic Sunroof", "Harman Kardon", "Head-Up Display"],
    location_city: "Jeddah",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "/seed-images/automotive%2F1556189250-72ba954cfc2b.jpg", price: 22000000, currency: "SAR", location: "Jeddah, Saudi Arabia" },
    thumbnail: "/seed-images/automotive%2F1556189250-72ba954cfc2b.jpg",
  },
  {
    id: "auto_seed_3",
    tenant_id: "default",
    seller_id: "seller_3",
    listing_type: "sale",
    title: "2024 Mercedes-Benz GLE 450",
    make: "Mercedes-Benz",
    model_name: "GLE 450",
    year: 2024,
    mileage_km: 2100,
    fuel_type: "hybrid",
    transmission: "automatic",
    body_type: "suv",
    color: "Obsidian Black",
    condition: "new",
    price: 32000000,
    currency_code: "SAR",
    description: "New Mercedes-Benz GLE 450 4MATIC with AMG Line, MBUX infotainment, and EQ Boost mild hybrid system.",
    features: ["AMG Line", "MBUX", "Burmester Audio", "Air Suspension"],
    location_city: "Dammam",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "/seed-images/automotive%2F1618843479313-40f8afb4b4d8.jpg", price: 32000000, currency: "SAR", location: "Dammam, Saudi Arabia" },
    thumbnail: "/seed-images/automotive%2F1618843479313-40f8afb4b4d8.jpg",
  },
  {
    id: "auto_seed_4",
    tenant_id: "default",
    seller_id: "seller_4",
    listing_type: "sale",
    title: "2023 Lexus ES 350 F Sport",
    make: "Lexus",
    model_name: "ES 350",
    year: 2023,
    mileage_km: 12000,
    fuel_type: "petrol",
    transmission: "automatic",
    body_type: "sedan",
    color: "Sonic Silver",
    condition: "certified_pre_owned",
    price: 16500000,
    currency_code: "SAR",
    description: "Lexus ES 350 F Sport with Mark Levinson audio, navigation, and advanced safety package.",
    features: ["F Sport Package", "Mark Levinson Audio", "Navigation", "Blind Spot Monitor"],
    location_city: "Riyadh",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "/seed-images/automotive%2F1621993202323-f438eec934ff.jpg", price: 16500000, currency: "SAR", location: "Riyadh, Saudi Arabia" },
    thumbnail: "/seed-images/automotive%2F1621993202323-f438eec934ff.jpg",
  },
  {
    id: "auto_seed_5",
    tenant_id: "default",
    seller_id: "seller_5",
    listing_type: "sale",
    title: "2024 Genesis G80 3.5T",
    make: "Genesis",
    model_name: "G80",
    year: 2024,
    mileage_km: 800,
    fuel_type: "petrol",
    transmission: "automatic",
    body_type: "sedan",
    color: "Vik Black",
    condition: "new",
    price: 19500000,
    currency_code: "SAR",
    description: "All-new Genesis G80 with 3.5L twin-turbo V6, Lexicon audio, and Genesis Connected Services.",
    features: ["Twin-Turbo V6", "Lexicon Audio", "Remote Smart Parking", "Highway Driving Assist"],
    location_city: "Jeddah",
    location_country: "SA",
    status: "active",
    metadata: { thumbnail: "/seed-images/automotive%2F1632245889029-e406faaa34cd.jpg", price: 19500000, currency: "SAR", location: "Jeddah, Saudi Arabia" },
    thumbnail: "/seed-images/automotive%2F1632245889029-e406faaa34cd.jpg",
  },
]

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  try {
    const mod = req.scope.resolve("automotive") as any
    const { limit = "20", offset = "0" } = req.query as Record<string, string | undefined>
    const filters: Record<string, any> = { status: "active" }
    const dbItems = await mod.listVehicleListings(filters, { skip: Number(offset), take: Number(limit) })
    const items = Array.isArray(dbItems) && dbItems.length > 0 ? dbItems : SEED_DATA
    return res.json({ items, count: items.length, limit: Number(limit), offset: Number(offset) })
  } catch (error: any) {
    return handleApiError(res, error, "STORE-AUTOMOTIVE-LISTINGS")
  }
}
