import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"

const SEED_DATA = [
  {
    id: "blog-1",
    slug: "the-future-of-e-commerce-in-2026",
    title: "The Future of E-Commerce in 2026",
    excerpt: "Explore the latest trends shaping online retail, from AI-powered personalization to sustainable packaging solutions.",
    content: "<p>The e-commerce landscape is evolving rapidly, driven by advances in artificial intelligence, changing consumer expectations, and a global push toward sustainability.</p><p>In 2026, we're seeing several key trends reshape the industry:</p><h2>AI-Powered Personalization</h2><p>Machine learning algorithms now power highly personalized shopping experiences, from product recommendations to dynamic pricing. Retailers using AI-driven personalization report up to 35% higher conversion rates.</p><h2>Sustainable Packaging</h2><p>Consumers increasingly demand eco-friendly packaging options. Brands that have adopted biodegradable and recyclable packaging materials have seen a 20% boost in customer loyalty.</p><h2>Social Commerce</h2><p>Social media platforms continue to integrate shopping features, making it easier than ever for consumers to discover and purchase products without leaving their favorite apps.</p>",
    category: "tech",
    author: "Sarah Mitchell",
    publishedAt: "2026-02-10T09:00:00Z",
    read_time: "6 min read",
    thumbnail: "/seed-images/content%2F1460925895917-afdab827c52f.jpg",
    tags: ["e-commerce", "technology", "trends"],
    reviews: [{ author: "Tech Reader", rating: 5, comment: "Great overview of current trends. Very well researched.", created_at: "2026-02-12T00:00:00Z" }, { author: "E-com Founder", rating: 4, comment: "Insightful article. The AI section was especially relevant.", created_at: "2026-02-11T00:00:00Z" }, { author: "Digital Marketer", rating: 5, comment: "Shared this with my team. Excellent analysis.", created_at: "2026-02-11T00:00:00Z" }, { author: "Retail Analyst", rating: 4, comment: "Good predictions backed by solid data.", created_at: "2026-02-10T00:00:00Z" }, { author: "Startup CEO", rating: 5, comment: "This helped shape our 2026 strategy.", created_at: "2026-02-10T00:00:00Z" }],
  },
  {
    id: "blog-2",
    slug: "10-tips-for-building-a-successful-online-store",
    title: "10 Tips for Building a Successful Online Store",
    excerpt: "From product photography to customer retention strategies, learn the essentials of running a thriving e-commerce business.",
    content: "<p>Building a successful online store requires more than just listing products. Here are 10 essential tips to help you thrive in the competitive e-commerce landscape.</p><h2>1. Invest in Professional Photography</h2><p>High-quality product images are your most powerful sales tool. Studies show that 93% of consumers consider visual appearance the key factor in purchasing decisions.</p><h2>2. Optimize for Mobile</h2><p>With over 70% of e-commerce traffic coming from mobile devices, a responsive design isn't optional—it's essential.</p><h2>3. Build Trust with Reviews</h2><p>Customer reviews significantly impact purchasing decisions. Encourage satisfied customers to leave reviews and respond professionally to negative feedback.</p>",
    category: "guides",
    author: "Ahmed Al-Rashid",
    publishedAt: "2026-02-08T14:30:00Z",
    read_time: "8 min read",
    thumbnail: "/seed-images/campaigns%2F1556742049-0cfed4f6a45d.jpg",
    tags: ["guides", "e-commerce", "business"],
    reviews: [{ author: "New Seller", rating: 5, comment: "Exactly what I needed. Clear and actionable tips.", created_at: "2026-02-09T00:00:00Z" }, { author: "Shopify Owner", rating: 4, comment: "Solid advice especially on mobile optimization.", created_at: "2026-02-09T00:00:00Z" }, { author: "Side Hustler", rating: 5, comment: "Followed these tips and saw immediate improvements.", created_at: "2026-02-08T00:00:00Z" }, { author: "Marketing Pro", rating: 4, comment: "Good fundamentals covered here.", created_at: "2026-02-08T00:00:00Z" }, { author: "Small Biz Owner", rating: 5, comment: "Wish I had this guide when I started.", created_at: "2026-02-08T00:00:00Z" }],
  },
  {
    id: "blog-3",
    slug: "smart-city-infrastructure-a-new-era-of-urban-living",
    title: "Smart City Infrastructure: A New Era of Urban Living",
    excerpt: "How IoT sensors, digital twins, and connected platforms are transforming the way cities operate and serve citizens.",
    content: "<p>Smart city technology is revolutionizing urban infrastructure, creating more efficient, sustainable, and livable cities around the world.</p><h2>IoT Sensor Networks</h2><p>Connected sensors monitor everything from air quality to traffic flow, providing real-time data that city planners use to make informed decisions.</p><h2>Digital Twins</h2><p>Virtual replicas of city infrastructure allow planners to simulate changes before implementing them, reducing costs and minimizing disruption.</p><h2>Connected Platforms</h2><p>Integrated platforms like CityOS bring together multiple city services into a single, unified system that improves both efficiency and citizen experience.</p>",
    category: "tech",
    author: "Dr. Fatima Khan",
    publishedAt: "2026-02-05T11:00:00Z",
    read_time: "10 min read",
    thumbnail: "/seed-images/content%2F1573164713988-8665fc963095.jpg",
    tags: ["smart-city", "technology", "infrastructure"],
    reviews: [{ author: "Urban Planner", rating: 5, comment: "Brilliant overview of smart city technology.", created_at: "2026-02-06T00:00:00Z" }, { author: "IoT Engineer", rating: 5, comment: "The digital twins section was spot on.", created_at: "2026-02-06T00:00:00Z" }, { author: "City Official", rating: 4, comment: "Very relevant for municipal planning.", created_at: "2026-02-05T00:00:00Z" }, { author: "Tech Journalist", rating: 4, comment: "Well-written and informative piece.", created_at: "2026-02-05T00:00:00Z" }, { author: "Sustainability Lead", rating: 5, comment: "CityOS platform sounds transformative.", created_at: "2026-02-05T00:00:00Z" }],
  },
  {
    id: "blog-4",
    slug: "sustainable-fashion-making-ethical-choices-easy",
    title: "Sustainable Fashion: Making Ethical Choices Easy",
    excerpt: "A guide to building a conscious wardrobe without compromising on style or breaking the bank.",
    content: "<p>Sustainable fashion is no longer a niche movement—it's becoming the standard. Here's how you can make ethical fashion choices without sacrificing style.</p><h2>Understanding Fast Fashion's Impact</h2><p>The fashion industry is one of the world's largest polluters. By choosing sustainable brands, you can help reduce waste, water usage, and carbon emissions.</p><h2>Building a Capsule Wardrobe</h2><p>A capsule wardrobe focuses on versatile, high-quality pieces that can be mixed and matched. This approach reduces waste and saves money in the long run.</p>",
    category: "lifestyle",
    author: "Layla Hassan",
    publishedAt: "2026-02-03T08:00:00Z",
    read_time: "5 min read",
    thumbnail: "/seed-images/content%2F1558171813-4c088753af8f.jpg",
    tags: ["fashion", "sustainability", "lifestyle"],
    reviews: [{ author: "Eco Shopper", rating: 5, comment: "Love the capsule wardrobe concept!", created_at: "2026-02-04T00:00:00Z" }, { author: "Fashion Blogger", rating: 4, comment: "Great tips on ethical fashion choices.", created_at: "2026-02-04T00:00:00Z" }, { author: "Minimalist", rating: 5, comment: "This changed how I think about clothing.", created_at: "2026-02-03T00:00:00Z" }, { author: "Style Editor", rating: 4, comment: "Practical and well-written guide.", created_at: "2026-02-03T00:00:00Z" }, { author: "Conscious Consumer", rating: 5, comment: "More people need to read this.", created_at: "2026-02-03T00:00:00Z" }],
  },
  {
    id: "blog-5",
    slug: "how-small-businesses-can-compete-in-the-digital-marketplace",
    title: "How Small Businesses Can Compete in the Digital Marketplace",
    excerpt: "Practical strategies for small business owners to leverage technology, social media, and marketplace platforms.",
    content: "<p>Small businesses have more tools than ever to compete with larger companies in the digital marketplace.</p><h2>Leverage Social Media</h2><p>Social media platforms offer free and paid tools to reach your target audience. Authentic engagement and storytelling can help small businesses build loyal communities.</p><h2>Use Marketplace Platforms</h2><p>Platforms like CityOS provide small businesses with enterprise-grade tools at affordable prices, leveling the playing field.</p>",
    category: "business",
    author: "Omar Khaled",
    publishedAt: "2026-01-28T16:00:00Z",
    read_time: "7 min read",
    thumbnail: "/seed-images/content%2F1454165804606-c3d57bc86b40.jpg",
    tags: ["business", "small-business", "digital"],
    reviews: [{ author: "Entrepreneur", rating: 5, comment: "Finally, practical advice for small businesses.", created_at: "2026-01-30T00:00:00Z" }, { author: "Business Coach", rating: 4, comment: "Great resource for my clients.", created_at: "2026-01-29T00:00:00Z" }, { author: "Marketplace Seller", rating: 5, comment: "The platform tips are gold.", created_at: "2026-01-29T00:00:00Z" }, { author: "Freelancer", rating: 4, comment: "Helpful strategies for building presence.", created_at: "2026-01-28T00:00:00Z" }, { author: "Local Shop Owner", rating: 5, comment: "Applied these and grew online sales by 30%.", created_at: "2026-01-28T00:00:00Z" }],
  },
]

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  const { slug } = req.params
  const seedItem = SEED_DATA.find(i => i.slug === slug || i.id === slug) || SEED_DATA[0]
  return res.json({ post: seedItem, item: seedItem })
}
